- adresse/templates/base.html
Bonus: adding `lang="fr"` to the `<html>` element?
> Valid HTML

- .gitignore
- next.config.js
- package.json
- yarn.lock
> Add bundle analyzer

- components/csv/csv.js
- components/csv/holder.js
Lorsque l'extension ou le type de fichier ne sont pas connus, on fait confiance à l'utilisateur.
https://stackoverflow.com/questions/7076042/what-mime-type-should-i-use-for-csv
> Amélioration de la détection de types de fichier

- components/api.js
- components/csv/geocoder.js
- components/csv/holder.js
- components/csv/table.js
- components/map/leaflet-map.js
- components/map/map-search.js
- components/map/search-input.js
- package.json
- pages/map.js
- yarn.lock
Le linting `xo` passe désormais.
> Diverses améliorations du code

- components/bal/csv-meta.js
- components/bal/fields.js
- components/bal/known-fields.js
- components/bal/line-value.js
- components/bal/line.js
- components/bal/row-errors.js
- components/bal/row.js
- components/bal/rows.js
- components/bal/unknown-fields.js
- components/bal/validateur-bal.js
- components/csv/csv.js
- components/tools.js
- package.json
- pages/validateur-bal.js
- yarn.lock
Outil en ligne permettant de valider la structure et le contenu d'une [Base Adresse Locale](https://cms.geobretagne.fr/content/travaux-gt-ban-aitf).
Plus d'informations à venir.
> Première implémentation du validateur BAL

- components/bal/file-handler.js
- components/bal/validateur-bal.js
- components/csv/holder.js
- components/input-form.js
- components/notification.js
Fix #95 Valider un fichier BAL distant
> Valider un fichier BAL distant 

- components/bal/validateur-bal.js
Fix #97 Fichier CSV non reconnu par le validateur BAL
> Accepte le Content-Type application/octet-stream

- components/csv/geocoder.js
> Réinitialise le formulaire en cas de changement

- components/api.js
- components/main-style.js
- Remplace `httpie` par `curl`
- Changement de la couleur de fond du code
> Mise à jour de la page API

- layouts/main.js
> Correctif compatibilité IE 11

- components/map/address-map.js
- components/map/centered-map.js
- components/map/index.js
- components/map/popup-address.js
La carte interactive récupère toutes ses facultés !   🎉
Fix #104
> Ajout du géocodage inverse

- components/bases-locales/index.js
- components/header.js
Ajout dans la barre de navigation
Mise en forme du texte
> Modifications page Base locales

- components/dropdown.js
- components/hamburger-menu.js
- components/header.js
- components/map/centered-map.js
- components/map/index.js
Ajout d'un menu hamburger sur mobile.
> Menu hamburger

- components/bases-locales/validator/file-handler.js
- components/bases-locales/validator/index.js
- components/bases-locales/validator/report/index.js
- components/notification.js
- lib/error.js
Le validateur essaye de mettre à jour l'url même quand celle-ci est `null`.
> Correction du Validateur BAL

- components/bases-locales/init-base/index.js
- components/bases-locales/init-base/search-communes.js
- components/search-input/render-commune.js
- Corrige la race condition sur l'auto-complétion (fix #139)
- Corrige l'affichage des collectivités d'outre-mer
- Limite le résultat à 5 communes
> Amélioration de la recherche de commune

- components/bases-locales/init-base/search-communes.js
- components/explorer/search-commune.js
- components/map/index.js
- components/search-input/index.js
> Corrige l'affichage des inputs sur mobile

- components/bases-locales/bases-adresse-locales/dataset/commune/index.js
- components/bases-locales/bases-adresse-locales/dataset/commune/voie/index.js
- components/bases-locales/bases-adresse-locales/dataset/commune/voie/voie-preview.js
- components/bases-locales/bases-adresse-locales/dataset/header.js
- components/bases-locales/bases-adresse-locales/dataset/index.js
- components/bases-locales/bases-adresse-locales/meta.js
- components/explorer/voie/address.js
- components/explorer/voie/infos.js
- components/tag.js
- lib/table.js
- lib/types.js
Ajout d'un tag permettant de distinguer les toponymes des voies.
fix #145
> Ajout d'un tag pour les toponymes

- components/bases-locales/bases-adresse-locales/dataset/commune/voie/numeros-map.js
- components/mapbox-gl/index.js
Le `maxZoom` est fixé à **18**.
#154 Zoom trop important lorsqu'il y a peu de points
> Ajout d'un zoom maximum pour l'affichage initial

- components/bases-locales/bases-adresse-locales/meta.js
- components/bases-locales/bases-adresse-locales/summary.js
- components/header.js
- Correction de l'affichage des meta d'un fichier BAL
- Correction des links de la barre de navigation
> Correction mineur du style

- .babelrc
- .circleci/config.yml
- .gitignore
- build/scripts/extract-bundles
- next.config.js
- package.json
- yarn.lock
> Update next.js, generate changelogs

- components/head.js
This caused an issue on the download page with nested paragraphs, which are forbidden.
> Replace paragraphs with divs in Head component

- package.json
- yarn.lock
> Update regenerator-runtime to 0.12.0

- components/bases-locales/validator/index.js
> Améliore la détection du format CSV

- components/bases-locales/init-base/search-communes.js
Fix #176 Debounce sur auto-complétion nom de commune
> Debounce sur auto-complétion nom de commune de l'initialisation BAL

- .circleci/config.yml
> Corrige la configuration CircleCI

- components/bases-locales/editor/edit-bal/init-base.js
- lib/bal/api.js
- next.config.js
- package.json
- pages/bases-locales.js
- pages/bases-locales/datasets.js
- pages/bases-locales/datasets/dataset.js
- pages/bases-locales/datasets/dataset/commune.js
- pages/bases-locales/datasets/dataset/commune/voie.js
- pages/bases-locales/datasets/dataset/report.js
- yarn.lock
> Rend configurable l'URL de l'API BAL

- components/map/address-map.js
Fix #136  Identifiant et libellé complet (carte)
> Ajoute l'identifiant et libellé complet au popup

- components/bases-locales/editor/edit-bal/context/commune/create-toponyme.js
- components/bases-locales/editor/edit-bal/context/voie/create-numero.js
- components/bases-locales/editor/edit-bal/context/voie/numero-form.js
- components/bases-locales/editor/edit-bal/context/voie/position-form.js
- components/bases-locales/editor/edit-bal/context/voie/single-position-map.js
- components/mapbox/map.js
Applique un fond photo aérienne à toutes les cartes éditables.
> Fond photo aérienne sur les cartes éditables

- components/bases-locales/bal-map/index.js
- components/bases-locales/bal-map/legend.js
- components/bases-locales/index.js
- components/mapbox/index.js
- components/mapbox/map.js
> Carte de déploiement des BAL

- components/bases-locales/editor/edit-bal/init-base.js
- lib/bal/api.js
- lib/error.js
- pages/bases-locales/editeur.js
- server/routes.js
`/bases-locales/editeur/commune/{codeCommune}`
> Nouvel accès directe pour l’édition d'une commune en particulier

- package.json
- yarn.lock
> Update jest-related dependencies

- package.json
- yarn.lock
> Update react to 16.7.0

- components/csv/csv.js
- components/csv/geocoder.js
Also fix `MAX_SIZE` by turning it into a Number (from a string…)
> Remove unsafe lifecycle in Csv and Geocoder components

- components/bases-locales/index.js
> Ajout du nombre de communes représentées dans les BAL

- components/commune-visualizer/create-address-menu.js
- package.json
- yarn.lock
Passage d'un test naïf de comparaison de préfixe sensible à la casse à du fuzzy-matching insensible à la casse et aux accents.
> [Éditeur] Améliore la comportement de l'auto-complétion de nom de voie

- components/bases-locales/publication/authentification.js
- components/bases-locales/publication/step.js
- components/bases-locales/publication/steps.js
Corrige des problèmes d'affichage de l'outil de publication
> Page publication responsive

- pages/donnees-nationales.js
- Ajout de la licence du produit gratuit issu de la BAN
- Mention de la décision du Premier ministre
- Mise à jour des informations concernant la diffusion principale
> MAJ page Données nationales

- components/ban-dashboard/ban-map.js
- components/ban-dashboard/ban-stats.js
- components/map/index.js
- components/mapbox/map.js
- lib/api-ban.js
- pages/dashboard-ban-2020.js
- La densité des adresses d'un département ou d'une commune est représenté par son opacité
- La popup suivant la souris est remplacé par un tooltip en haut à droite de l'écran
- Les couleurs sont réajustées
- Corrige les problèmes d'affichage sur mobile
> Améliorations cosmétique et prise en charge de la densité des adresses

- pages/api.js
Ajoute les nouveaux champs retournés par l'API depuis la mise à jour de mi-juillet.
> Mise à jour de la documentation de l'API

- components/explorer/explore-search.js
- components/explorer/header.js
- components/hero.js
- components/input-form.js
- pages/explore.js
- pages/explore/commune.js
- pages/explore/commune/voie.js
- pages/index.js
- static/images/city-background.svg
La recherche d'adresses est mise en avant et devient le cœur de cette nouvelle page d'accueil. Elle permet de rechercher et consulter communes, voies et numéros.
> Nouvelle page d'accueil

- components/mapbox/map.js
- components/mapbox/switch-map-style.js
> Fix Issue #460 - Barres de défilement supprimées

- components/bases-locales/bal-cover-map.js
> Supression de la mention null dans le popup de la carte "Bases locales"

- components/ie-warning.js
- layouts/main.js
> Avertissement IE 10+

- components/explorer/commune/voies-table.js
- components/explorer/voie/addresses-table.js
> Suppression de la colonne "Active"

- components/explorer/voie/index.js
- components/explorer/voie/map-container.js
- components/mapbox/layers/positions.js
- components/mapbox/map.js
- Corrige un bug d'affichage des positions d'un numéro restant affichées quand la page était directement chargé sur celui-ci.
- Recentre la carte sur le nouveau numéro quand celui-ci ne fait pas parti de la voie déjà chargée.
> Corrige le rafraichissement de la carte

- components/explorer/voie/head.js
- components/explorer/voie/index.js
> Ajout d'un fil d'Ariane

- components/bases-locales/bases-adresse-locales/dataset/commune/index.js
- components/bases-locales/bases-adresse-locales/dataset/index.js
Correction du Bug sur la recherche qui ne fonctionnait pas avec accent ou lettre capitale.
> Recherche des voies insensible à la casse (Explore, BAL)

- components/footer.js
- components/open-licence-ribbon.js
Passage des liens externes de `<Link>` à `<a>`.
> Correction des liens 

- components/hero.js
- components/icons/contribute.js
- components/icons/download.js
- components/icons/tools.js
- Amélioration du cercle entourant les icônes
- Ajout de la source des svg `feathericons.com`
> Amélioration des icônes 

- components/header.js
- components/tools.js
> Corrige l'erreur de lien vers l'API Géo

- .env.sample
- lib/explore/api.js
> Corrige l'erreur 500 provoqué par un mauvais code voie

- components/explorer/commune/voies-table.js
> Fix #539 - Correction du tri dans explore

- components/explorer/commune/index.js
Fix #543 
Correction du bug d'affiche de la carte dans Firefox.
> Correction du bug d'affichage dans Firefox

- public/schemas/adresses-csv.md
> Correction adresse-csv.md

- components/explorer/voie/index.js
> Affiche les suffixes dans explore/voie

- components/csv/geocoder.js
- lib/api-adresse.js
Fix #566 
Les messages d'erreur sont maintenant explicites.
> Ajout de messages d'erreurs dans le geocodeur

- components/csv/csv.js
> Corrige l'erreur 500 provoquée par un fichier csv vide 

- components/explorer/commune/index.js
- components/explorer/commune/statistics.js
- components/explorer/commune/voies-commune.js
- components/mapbox/hooks/load-data.js
- pages/explore/commune.js
> Cache les diagrammes de source lorsqu'on utilise la BAL

- .env.sample
- lib/bal/api.js
- package.json
- server.js
- yarn.lock
Reverts etalab/adresse.data.gouv.fr#596
> Revert "Ajout d'un proxy vers le backend"

- .env.sample
- components/footer.js
- components/header.js
- components/question.js
- components/search-commune-contact/index.js
- components/search-commune-contact/mairie-contact.js
- components/search-input/render-commune.js
- lib/api-etablissements-public.js
- pages/contact.js
- pages/faq.js
- server.js
> Page "Nous contacter"

- components/bases-locales/bases-adresse-locales/dataset/commune/bal-voies-table.js
- components/bases-locales/bases-adresse-locales/dataset/commune/index.js
- components/bases-locales/bases-adresse-locales/dataset/index.js
- components/bases-locales/bases-adresse-locales/index.js
- components/csv/csv.js
- components/csv/step.js
- components/explorer/explore-search.js
- components/explorer/voie/index.js
- components/hero.js
- components/map/index.js
- components/search-commune-contact/index.js
- components/search-commune-contact/mairie-contact.js
- components/search-input/index.js
- components/selectable-item-list.js
- components/sources-table.js
- components/table-list/index.js
- components/table-list/table-control.js
- components/table-list/table/body.js
- components/table-list/table/index.js
- lib/api-geo.js
- pages/faq.js
- pages/map.js
- Erreur de `propTypes`
- Avertissement `ValidateDOMNesting`
- Lien sans balise <a>
- Faute de frappe
- Désactiver le pied de page sur la carte interactive
- Position relative de la barre de recherche et de ses résultats
- Position `z-index` de l'input sur la carte
- Affichage des noms de colonne trop long dans le geocodeur
- Ajout du paramètre `limit` à `getCommunes`
- Ajout de l'option `boost` pour la recherche de commune
- Ajout d'un chargement pendant la récupération des informations de contact d'une mairie
- Ajout d'un chargement pendant l'analyse d'un fichier CSV
- Suppression de l'effet de fondu sur la liste de voies/adresse
- Amélioration de l'affichage des informations de contact d'une mairie sur mobile
> Correctifs et amélioration UX

- components/bases-locales/bases-adresse-locales/dataset/commune/index.js
- components/explorer/commune/voies-commune.js
> Ajout du code voie à la liste des voies

- components/bases-locales/index.js
- components/ribbon.js
- pages/contribuer.js
- pages/faq.js
- pages/index.js
Add link to BAL documentation in pages : 
- Bases-Locales
- Index
- FAQ
> Add BAL Guide's links

- components/bases-locales/publication/authentification.js
- components/bases-locales/publication/steps.js
- components/section.js
- pages/bases-locales/publication.js
- Ajout d'un bouton permettant de retourner sur l'éditeur de BAL. Ce bouton est accessible à toutes les étapes du formulaire.
- Correction de système d'étape. Celui-ci affiche correction les étapes terminée, en cours et à venir.
- Correction mineur de style
> Amélioration et correction de la page de publication

- components/bases-locales/validator/report/issue-rows.js
- components/bases-locales/validator/report/known-fields.js
- components/bases-locales/validator/report/line.js
- components/bases-locales/validator/report/row-issues.js
- components/bases-locales/validator/report/row.js
- components/bases-locales/validator/report/summary.js
- Correction d'une erreur au survol d'une anomalie
- Diverses améliorations esthétiques
> Validateur - modifications graphiques et fonctionnelles

- components/infolettre.js
- pages/index.js
- Mise en place d'un nouveau composant pour l'inscription à l'infolettre
> Mise à jour du composant d'inscription à l'infolettre

- components/bases-locales/bases-adresse-locales/dataset/header.js
- components/bases-locales/publication/authentification.js
- components/bases-locales/publication/user.js
- components/doc-download.js
- components/explorer/explore-search.js
- components/explorer/voie/index.js
- components/footer.js
- components/header.js
- components/mapbox/switch-map-style.js
- package.json
- pages/404.js
- pages/_app.js
- pages/_document.js
- pages/bases-locales/publication.js
- pages/bases-locales/validator.js
- pages/cgu.js
- pages/contact.js
- pages/contribuer.js
- pages/csv.js
- pages/donnees-nationales.js
- pages/faq.js
- pages/guides.js
- pages/index.js
- pages/tools.js
- yarn.lock
- Utilisation du composant `<Image>` de Next.js permettant l'optimisation du chargement des images
- Ajout de la page `/404.js` nécessaire à la page d'erreur customisée
- Utilisation de la résolution automatique des href
- `Anonymous arrow functions cause Fast Refresh to not preserve local component state.`
- `viewport meta tags should not be used in _document.js’s <Head>.` https://err.sh/next.js/no-document-viewport-meta
- `Your custom Document (pages/_document) did not render all the required subcomponent.`
- `Missing component: <Html />` https://err.sh/next.js/missing-document-component
- `The static directory has been deprecated in favor of the public directory.` https://err.sh/vercel/next.js/static-dir-deprecated
- `You have opted-out of Automatic Static Optimization due to …
> Mise à jour Next.js

- components/question.js
Et je me dis qu'au clic, ce slug peut être ajouté au hash de `window.location`.
> Calcule un ID de question

- next.config.js
Issue #720
- Ajout de `static.data.gouv.fr` dans next.config.js
> Ajout du domaine fournissant les logos des BAL dans next.config

- components/bases-locales/bases-adresse-locales/dataset/commune/voie/index.js
Issue #734 
- *avant :*
- *après :*
> Correction du bug affichant le mauvais Header

- components/explorer/explore-search.js
- Texte ajouté : `Rechercher une adresse, une voie, un lieu-dit ou une commune dans la Base Adresse Nationale`
*edit : Add more visibility to text help*
> Ajout d'un texte d'aide au dessus de la barre de recherche

- components/hero.js
> Fix #730 
- Suppression de media-queries inutiles.
> Correction du problème d'affichage sur la page d'accueil sur smartphone

- components/mapbox/ban-map/index.js
- components/mapbox/center-control.js
- layouts/base-adresse-nationale.js
- pages/base-adresse-nationale.js
- Prise en compte du hash dans la barre d'adresse
- Ajout d'un bouton de control pour centrer la carte
*capture vidéo*
https://user-images.githubusercontent.com/45098730/104205114-52d74300-542e-11eb-87b5-5b8b4ee4d17f.mp4
> Activation du "hash" et ajout d'un bouton pour centrer la carte

- components/bases-locales/publication/manage-file.js
- components/bases-locales/validator/file-handler.js
- components/bases-locales/validator/index.js
- components/csv/csv.js
- components/csv/holder.js
- lib/bal/api.js
- pages/bases-locales/publication.js
> Permet la publication de fichier CSV

- temoignages.json
Ajout du témoignage de Bréau-Mars du 11/02/2020
> Ajout du témoignage de Bréau-Mars

- components/bases-locales/bases-adresse-locales/dataset/communes-preview.js
- components/bases-locales/bases-adresse-locales/dataset/index.js
- components/bases-locales/bases-adresse-locales/summary.js
- components/bases-locales/index.js
- lib/bal/api.js
- pages/bases-locales/datasets/dataset.js
Adaptation du code pour utiliser la nouvelle API d'exposition des métadonnées des BAL
> Mise en conformité de l'interface de consultation des BAL

- components/bases-locales/publication/manage-file.js
- lib/bal/api.js
- pages/bases-locales/publication.js
- Change l'étape du formulaire lorsque que la publication réussie
- Affiche un message d'erreur lorsque le téléversement du fichier CSV échoue
> Correction du processus de publication

- components/bases-locales/bases-adresse-locales/index.js
- components/bases-locales/publication/published.js
- components/button-link.js
- components/incendie-ovh.js
- pages/_app.js
- pages/bases-locales/publication.js
- pages/contact.js
- pages/faq.js
- pages/gerer-mes-adresses.js
Cette PR désactive tous les liens vers "Mes Adresses" et met à jour le message sur la page d'accueil.
> Indisponibilité de Mes Adresses

- partners.json
Just update the SOGEFI' link in partners.json.
> Change sogefi link

- components/ban-search.js
> Affiche les lieux de type "locality" dans la barre de recherche

- components/bases-locales/charte/partner.js
- components/bases-locales/charte/search.js
- components/bases-locales/charte/tags.js
- lib/api-geo.js
- partners.json
1. - Ajout d'une recherche par code postal 
2. - Amélioration du système de filtrage par tags : 
- Abandon de la liste de tags à remplir manuellement pour une mise à jour automatique de la liste de tags à travers la liste complète des partenaires.
-    Les tags ne correspondant pas au(x) partenaire(s) trouvé(s) sont grisés et le click event est désactivé .
-    La liste de tags n'apparait que lorsque la recherche a aboutie
> Amélioration de la barre de recherche des partenaires

- partners.json
> Suppression du partenaire CRIGE PACA

- temoignages.json
> Ajout du témoignage de Mégalis Bretagne

- partners.json
> Ajoute CRIGE aux partenaires

- components/bases-locales/charte/partner.js
- components/bases-locales/charte/partners.js
- pages/bases-locales/charte.js
- pages/index.js
- partners.json
Les partenaires faisant office de sociétés privées sont maintenant séparé du reste des partenaires.
Les logos sur la page d'accueil sont également supprimés car leur présence n'est à présent plus d'aucune utilité et surchargent la page
.
> Ajout d'une section "société" dans la liste des partenaires

- pages/guides.js
Ajout de la fonctionnalité d'association des parcelles aux adresses au guide.
> Mise à jour du guide Mes Adresses

- pages/faq.js
> MAJ entrée FAQ fréquence de mise à jour

- components/infolettre.js
Lien vers la section infolettre : https://adresse.data.gouv.fr/#newsletter
Fix #833
> Ajout d'une ancre vers la section Infolettre

- layouts/base-adresse-nationale.js
- pages/base-adresse-nationale.js
> Corrige la hauteur de la vue BAN mobile

- pages/guides.js
- Modification du texte dans la section "Mes Adresses" afin de permettre l'ajout du lien vers le guide de Mes Adresses.
> Ajout d'un lien vers le guide de Mes Adresses

- pages/guides.js
> Ajout d'un lien vers "le guide des bonnes pratiques"

- package.json
- server.js
- yarn.lock
https://github.com/helmetjs/helmet
> Active helmet en production (sécurité)

- pages/index.js
Simple modification du CSS pour s'adapter au nouveau design
Ajout d'un bouton de redirection vers [/donnees-nationales](https://adresse.data.gouv.fr/donnees-nationales)
> Refonte de la section sous l'illustration de la page d'accueil

- components/bases-locales/charte/partner.js
- pages/gerer-mes-adresses.js
Mise à niveau de la page /gerer-mes-adresses avec le nouveau design de adresse.data
> Amélioration du design de la page gérer mes adresses

- partners.json
> Modifications de la liste des services de TIGEO

- components/maplibre/map.js
Le changement de fond de carte n'est plus disponible depuis #956.
Cette PR corrige cette fonctionnalité en introduisant de nouveau le suivi de l'état du chargement du style de la carte.
Avant basé sur l'événement `styledata`, c'est désormais l'évènement `style.load` qui est utilisé car plus adapté à cette utilisation.
> Corrige le changement de fond de carte

- components/frise.js
Gestion des dates de l'hiver en prenant en compte la date du solstice de l'année précédente.
> Fix des dates de l'hiver

- components/search-commune-contact/mairie-contact.js
- pages/contribuer.js
> Amélioration de l'affichage des infos de contact de mairie

- components/commune/bal-state.js
- components/commune/download-adresses.js
- components/commune/historique-item.js
- components/commune/historique.js
- lib/api-depot.js
- pages/commune/[codeCommune].js
- Correction de soucis de wording.
- Correction du design des items d'historique.
- Ajout d'une url vers les bal de chaque révision (items d'historique).
> Améliorations de la page commune

- pages/index.js
Close #1020
Cette PR ajoute une ancre vers la section `Obtenez des informations sur les adresses d’une commune` sur la page d'accueil afin de pouvoir préciser un hyperlien dans la documentation et les fiches Reflex informer, communiquer sur vos adresses...
URL : [https://adresse.data.gouv.fr/#rechercher-une-commune](https://adresse.data.gouv.fr/#rechercher-une-commune)
> Ajout d'une ancre 

- pages/guides.js
Mise en ligne de la v5.0 du guide de Mes Adresses.
- Modification de l’information sur l’authentification (à la Base Adresse Locale et non plus à la commune)
- Ajout de paragraphes liés aux statuts de la Base Adresses Locale
- Modification des captures d’écran de publication de la Base Adresse Locale
- Ajout de la mention du fond de carte IGN
- Modification d'illustrations pour montrer des fonds IGN
> Guide Mes Adresses Guide en v5.0

- pages/guides.js
Mise à jour du Guide des Bonnes Pratiques de la v2.1 à la v3.0.
La version 3 du Guide des Bonnes pratiques actualise les pages :
- Ajout de la LOI 3DS dans la partie cadre légal.
- Modification des exemples d’arrêtés pour ajouter la dénomination des lieux-dits et retirer « à la charge de la commune pour la pose de la première plaque ».
- Ajout des paragraphes « Continuité des voies entre communes », « Les adresses avec accès par la commune voisine », « Les adresses des lotissements et ensembles privés ».
Fix #1044
> Mise à jour du Guide des Bonnes Pratiques en v3.0

- components/commune/bal-state.js
- components/commune/historique-item.js
Défini par défaut l'habilité par la commune si aucune organisation n'est renseignée.
Close #1041
> Correction erreur 500 page commune

- events.json
> Ajout d'un lien vers le formulaire d'inscription webinaire 14/04/22

- layouts/base-adresse-nationale.js
Modification dans l'explorateur en bas de page de "Gérer mes adresses" par "Contribuer".
Fix  #1049
> remplacement gerer mes adresses par contribuer

- components/bases-locales/charte/partner.js
- components/evenement/event-modal.js
- lib/tag.js
Une fonction de traitement de strings pour la création de tag a été crée il y a un moment pour les partenaires.
Hors, une autre fonction bien plus perfectionnée a été crée lors de la création de la page évènements.
Cette PR : 
- Déplace la fonction de traitement perfectionnée de tag dans le dossier /lib afin qu'elle puisse être importée et éviter les répétitions de code.
- Améliore la fonction pour qu'elle accepte les accents (minuscule et majuscule)
Close #1064
> Amélioration de la gestion de traitement des tags

- components/bases-locales/publication/published.js
- pages/bases-locales/publication.js
- Mise à jour du wording.
- Ajout de bouton permettant à l'utilisateur d'être rediriger vers les pages contenant les informations associées au différentes sections.
Close #1063
> MAJ écran affichant la publication par formulaire de dépôt

- pages/contact.js
- Redirection vers la page `/gerer-mes-adresses` au lieu de rediriger vers la création d'une base locale.
- Correction coquille dans le texte de `Pour toute autre demande ou pour plus d’informations`.
- Ajout d'un lien vers la FAQ
> Modifications sur la page /contact

- partners.json
> Modification du lien du partenaire Megalis

- events.json
Modification Webminaire du 14-04-2022
Issue #1083
> Modification events webinaire

- pages/ressources.js
- Mise à jour du Guide Mes Adresses en v6.0
- Correction du lien vers le Guide des Bonnes Pratiques v3.1
Fix #1144
> Mise à jour du Guide Mes Adresses v6.0

- events.json
Les wébinaires Mes Adresses aux dates du 7 et 21 avril ont été ajoutés à event.js
> Ajouter des dates a event.js

- events.json
Ajout de la date événement Partenaires Charte le 12 Juillet à event.js
Close #1149
> Ajout date event.js

- pages/donnees-nationales.js
passage d'une fréquence hebdo à mensuelle pour le calcul du flux BAN pour l'instant
> modification des frequences de MAJ flux BAN

- pages/ressources.js
Cette PR ajoute du wording supplémentaire permettant à l'utilisateur d'être informés que les guides sont régulièrement mis à jour et qu'ils doivent vérifier s'ils utilisent la bonne version.
Close #1169
> Ajout wording concernant l'actualisation des guides au format PDF

- package.json
- yarn.lock
La dépendance n'était pas utilisée.
> Suppression de project-legal

- events.json
Ajout Evenement Adresse_Lab#3 sur page evenements
Ticket : https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1184
> Ajout Evenement Adresse_Lab#3 sur page evenements

- events.json
2 Wébinaires Mes Adresses + Un évènement partenaires (https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1208)
> Ajout de 3 dates à event.js

- components/base-adresse-nationale/tooltip.js
- components/bases-locales/validator/report/fields/found-fields.js
Cette PR affiche les informations d'une langue régionales si celle-ci est détectée par le validateur.
Close #1245
> Intégration de la langue régionale dans le validateur

- components/evenement/event-banner.js
Le système de carrousel n'était pas du tout adapté aux lecteurs d'écran ou pour les personnes ayant des troubles de la concentration/lecture avec des slides automatiques.
Ce PR mets le carrousel aux normes basiques d'accessibilité en permettant à l'utilisateur de mettre le défilement automatique en pause et aux lecteurs d'écran de pouvoir lire les dates des évènements.
> Gérer l'accessibilité sur la bannière des évènements

- components/base-adresse-nationale/addresses-list.js
- components/base-adresse-nationale/commune/index.js
- components/base-adresse-nationale/explorer.js
- components/bases-locales/validator/file-handler.js
- components/bases-locales/validator/report/fields/found-fields.js
- components/bases-locales/validator/report/fields/unfound-fields.js
- components/bases-locales/validator/report/file-validation.js
- components/bases-locales/validator/report/index.js
- components/bases-locales/validator/report/summary/index.js
- components/bases-locales/validator/report/summary/issues-sumup.js
- components/bases-locales/validator/validator-section-title.js
- components/blog-card.js
- components/doc-download.js
- components/donnees-nationales/intro.js
- components/post.js
- pages/blog/index.js
- pages/ressources.js
Une bonne hiérarchie de titres permet aux utilisateurs de :
-  se situer rapidement dans une page
-  s’assurer d’être au bon endroit.
Pour cela, la hiérarchie est complète et cohérente (pas de trous entre les titres de niveaux 1, 2, 3…)
Close #1201
> Hiérarchie des titres pertinente

- lib/util/contours-communes.js
- Renomme `BAN_API_URL` -> `API_BAN_URL`
- `API_BAN_URL` = `NEXT_PUBLIC_API_BAN_URL`
> Renomme la variable BAN_API_URL et sa valeur : fait référence à la variable d'environnement NEXT_PUBLIC_API_BAN_URL

- events.json
Ajout des dates de webinaires mes adresses pour novembre
Fix #1317
> Ajout des webinaires Mes Adresses de novembre

- events.json
Ajout date evenement partenaire 
Fix #1319
> Ajout evenement partenaire

- events.json
Ajout de l'évènement adresseLab identifiant unique du 09 Novembre
Fix #1265
> Ajout adresseLab identifiant unique

- components/ban-search.js
Suppression de la regex qui est erronée en attendant une correction.
> Correction recherche adresse

- components/ban-search.js
- lib/api-adresse.js
- lib/string.js
- Utilisation de la fonction `isFirstCharValid` venant de l’[api-geocode](https://github.com/BaseAdresseNationale/api-geocode/blob/863bf5f7c5962b42ff524ff1c2e72b2e85a03ca1/lib/addok.js#L10)
- Ajout d’un `useEffect` pour nettoyer les résultats de recherche qui s'affichaient après avoir effacé le champ de recherche
> Corrige le problème de la barre de recherche en page d’accueil

- events.json
Ajout des webinaires Mes adresses de Décembre
Fix #1333
> Ajout webinaires Décembre

- events.json
Ajout de trois nouveaux évènements au calendrier
Fix #1399
> Ajout de nouveaux évènements

- events.json
Ajout de 13 dates de wébinaires Mes Adresses pour les mois de février, mars et avril 2023.
> Ajout de dates de wébinaires

- events.json
> ajout event adresseLab5

- components/base-adresse-nationale/layout-selector.js
- components/bases-locales/charte/partner.js
- components/maplibre/switch-map-style.js
- pages/bases-locales/charte/index.js
> Fix: Alt img attribute should be a string and not a boolean

- pages/gerer-mes-adresses.js
> Correction de fautes

- components/base-adresse-nationale/voie/index.js
- pages/base-adresse-nationale.js
This pull request aims to add street and address list for lieu-dit on map explorer by adding, when you click on a lieu-dit : 
- List of street associated with the lieu-dit
- List of addresses associated to each street
> Added address and street for lieu-dit on map explorer

- components/maplibre/map.js
Cette PR va ajout d'un indicateur d'échelle sur la carte.
Avant :
Apres :
> Add Scale controle to map

- components/base-adresse-nationale/parcelles-list.js
"Aucune parcelles cadastrale" corrigé en "Aucune parcelle cadastrale"
> orthographic correction

- components/alert.js
- components/base-adresse-nationale/explorer.js
- components/bases-locales/charte/commune.js
- components/evenement/event-banner.js
- components/know-more-section.js
- components/maplibre/select-paint-layer.js
- components/maplibre/switch-map-style.js
- components/notification.js
- layouts/base-adresse-nationale.js
- pages/donnees-nationales/index.js
- pages/donnees-nationales/utilisateurs.js
- styles/template-data-gouv-to-dsfr/main-alternate.css
- styles/template-data-gouv-to-dsfr/main-alternate.scss
Avant :
Après :
Avant :
Après :
> Ajustement de certains composants suite au passage au DSFR

- events.json
Ajout dates webinaires Mes Adresses pour les mois de mai, juin, juillet, aout.
> Ajout dates webinaires Mes Adresses

- components/footer.js
- pages/api-doc/index.js
Maj lien uptimerobot. retour à l'ancienne url
Fix #1507
> Maj link uptimerobot

- pages/bases-locales/publication.js
https://github.com/BaseAdresseNationale/mes-adresses/issues/792
> Fix props name codeCommune to Published component

- Dockerfile.dev
Fix local deployment with docker
> Fix Dockerfile.dev by creating a public folder before installing dependencies

- components/bases-locales/publication/published.js
- pages/bases-locales/publication.js
Issue : https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1532
> Le bouton "Publier une autre BAL" ne ramène pas au début du formulaire

- components/bases-locales/publication/manage-file.js
- components/bases-locales/validator/index.js
- components/bases-locales/validator/report/fields/index.js
- components/bases-locales/validator/report/fields/unfound-fields.js
- components/bases-locales/validator/report/index.js
- components/bases-locales/validator/report/profile-validation/profile-validation.js
- components/bases-locales/validator/report/profile-validation/table-profile-validation.js
- components/bases-locales/validator/report/summary/index.js
- components/bases-locales/validator/report/text-is-valid.js
- package.json
- yarn.lock
https://github.com/BaseAdresseNationale/validateur-bal/issues/76
https://github.com/BaseAdresseNationale/api-depot/issues/89
- Mise a jour de la page validation
https://github.com/BaseAdresseNationale/validateur-bal/pull/75
https://github.com/BaseAdresseNationale/validateur-bal/issues/74
> update validator 2.15.0

- events.json
Septembre  
mardi 5 - lvl 2  
jeudi 7 - lvl 1  
mardi 12 - lvl 2  
jeudi 21 - lvl 1  
jeudi 28 - lvl 1
Octobre  
jeudi 5 - lvl 1  
jeudi 12 - lvl 1  
jeudi 19 - lvl 2  
jeudi 26 - lvl 1
Novembre  
jeudi 2 - lvl 1  
jeudi 9 - lvl 2        
jeudi 16 - lvl 1  
jeudi 23 - lvl 2  
jeudi 30 - lvl 1
> Add webinaire dates to events.json

- pages/blog/index.js
Ajouter la carte des témoignages sur la page d'accueil du blog
> add partner map on blog page

- components/bases-locales/validator/index.js
- components/bases-locales/validator/validateur-documentation/index.js
- components/bases-locales/validator/validateur-documentation/list-documentation.js
- components/bases-locales/validator/validateur-documentation/profile-documentation.js
- components/bases-locales/validator/validateur-documentation/table-documentation.js
- package.json
- pages/bases-locales/validator-documentation.js
- yarn.lock
Pour le moment il n'y a aucune documentation sur a quoi sert et comment fonctionne  le validateur.
Ajout d'une documentation sur la page validateur avec l'explication des profiles, et les différentes alerte et erreurs de chacun
> Documentation validateur

- events.json
Modification du lien de la réunion pour l'adresse lab du 26 Septembre
Fix #1617
> Modif lien adresse lab 26 Septembre

- components/maplibre/styles/vector.json
Ajout intitulé département sur la carte à partir du niveau de zoom 5 jusqu'au niveau de zoom 9
Fix #1635
> Ajout intitule departement sur carte

- events.json
https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1639
> add event 2023-11-14

- events.json
Ajout de l'adresse lab du 12 Décembre 
Fix #1652
> Ajout evenenement adresse-lab

- events.json
Ajout evènement du 14 Novembre pour rencontre utilisateurs nationaux
Fix #1654
> ajout journee utilisateurs ban

- events.json
Ajout d'événements webinaire Mes Adresses et Partenaires de la Charte.
> Mise à jour events.json

- events.json
- Ajout événement  Réunion utilisateurs du 23 Janvier 2024 
- Ajout événement Adresse Lab du 08 02 2024
Fix #1684  Fix #1685
> Ajout evenement pour BAN

- events.json
Ajout date partenaires 13 février
> Ajout date partenaires 13 février

- events.json
Ajout événement rencontre utilisateurs du 19 Mars 2024
Fix #1699
> Ajout evenement rencontre utilisateur 19 Mars

- events.json
Ajout adresse lab Point trimestriel T2 2024
Fix #1701
>  AJout adresse Lab

- components/maplibre/ban-map/layers.js
cf  https://github.com/BaseAdresseNationale/ban-plateforme/pull/404
> Optimisation des noms des sources sur l'explorateur

- .env.default
- lib/util/contours-communes.js
- package.json
- yarn.lock
Maj dependance pour decoupage-administratif : modification valeur 2023 par 2024
> Maj pour cog 2024

- package.json
- yarn.lock
- Correction du bug d'interprétation champ uid_adresses
> validateur v2.19.1

- pages/stats.js
- views/stats/helper.js
issue 
https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1750
> Correction editoriale page stats

- components/bases-locales/charte/partenaires/index.js
- pages/bases-locales/charte/partenaires/[id].js
Un partenaire peut avoir plusieurs organisations sur datagouv
> feat: multi orga in partenaire

- pages/donnees-nationales/index.js
Changement du texte mise à jour mensuelle par mise à jour hebdomadaire sur la page https://adresse.data.gouv.fr/donnees-nationales
Close: #1771
> Maj texte actualisation des données

- .env.default
- components/hero.js
- lib/updated-date.js
- pages/api-doc/adresse.js
- pages/index.js
> ajout de la date d actualisation du moteur de recherche

- components/bases-locales/publication/code-authentification.js
- components/bases-locales/publication/publishing.js
- lib/proxy-api-depot.js
- pages/bases-locales/publication.js
- server/proxy-api-depot.js
Contexte : https://mattermost.incubateur.net/betagouv/pl/cua7979a8jbuxkia4qw1quzgqa
> fix: formulaire de publication for api depot migration

- pages/bases-locales/charte/index.js
> wording: charte société

- events.json
Add adress Lab T4 10 Septembre 2024
Close: #1790
> Add adresse Lab 10 Septembre

- events.json
Modification texte pour l'adresse lab
> Modif Texte adresselab

- src/layouts/Header.tsx
Modification text "Publication" by text "Publication des adresses" in "Les outils"
Add link on "Supervision BAL/ BAN" in menu "Les outils"
> Refonte:Change text and links in menu

- lib/util/compute.js
changement dans l'api-mes-adresse
> hot fix : deploiement-bal

- events.json
Ajout réunion utilisateurs du 25 Septembre 2025
Close: #1832
> Add events 25 Septembre

- src/app/outils/telechargements/page.tsx
Modification lien MVT, WFS, WMS
Suppression du bloc adresses extraites du cadastre
Close #1842
> Modif page Telecharger les donnees

- public/markdown/les_donnees_de_la_BAN.md
- src/app/outils/telechargements/page.tsx
Sur la page téléchargement modifications texte et liens
Close: #1848
> [refonte]Modification text et liens

- public/markdown/mentions-legales.md
Modifications des mentions légales
Close: #1858
> Changement mentions legales

- src/app/outils/page.tsx
Modification organisation de la page + text
> Modification page outils

- events.json
Ajout de la réunion utilisateurs du 05 Décembre
> Ajout evenement

- src/app/outils/page.tsx
- src/layouts/Header.tsx
-Ajout lien pour la newsletter dans le menu
** Page outils**
- Modification lien sur l'explorateur BAN
- Modification texte
- Ajout nouvel outil CRAIG dans 'outils de la communauté"
> Modif divers outils

- lib/api-geo.js
- pages/deploiement-bal.js
https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1899
> Fix dept with com

- pages/api-doc/index.js
Add api topo2fantoir in page api-doc api
Close #1915
> Add api topo2fantoir

- src/components/SectionSearchBAN/SectionSearchBAN.tsx
Sur la home page en dessous de la barre de recherche modification des textes liens en bouton
> Modification type button barre recherche home

- src/components/SearchBAN/SearchBAN.tsx
Nous n'affichons plus la région pour les DOM-TOM dans la recherche Home + Carte
Close #1933
> Correction bug affichage region Dom-TOM

- events.json
Ajout adresse Lab T1 2025
Close : #1938
> Add event BAN T1 2025

- next.config.mjs
- public/markdown/decouvrir-la-BAN.md
- src/app/layout.tsx
- src/data/sample-ban-info.json
- src/views/data/utils/helper.ts
Modif Links
Manage route redirections
> Modifs link et route

- next.config.mjs
Update other redirect link
Add rewrite url for adresses-odbl
> Update redirect et rewrite url

- modules.d.ts
- src/components/FormulaireDePublication/index.tsx
- src/components/ValidateurBAL/ValidationAccordion.tsx
- src/components/ValidateurBAL/ValidationReport.tsx
- src/components/ValidateurBAL/index.tsx
Après la mise en prod du nouveau site, il y a quelques fixs a faire:
- Enlever le stepper
- Bug délimiteur faux
- Champs présent en minuscules
- Tableaux tronqué
- Colorisation des champs des tableau
> fix: page validateur

- src/lib/data-service.ts
Modified max sockets value on s3 client using : https://docs.aws.amazon.com/sdk-for-javascript/v3/developer-guide/node-configuring-maxsockets.html
> Modified maxSockets values on s3 client to 200

- src/data/sample-quotes.json
Changement témoignage home page
Fix: #1988
> Change temoignage home

- src/pages/api/health.ts
> ajout du health route

- public/exemples/reverse.csv
- public/exemples/search.csv
Add example file on page api-adresse
> add example file geocodeur

- src/data/ban-events.json
Change text title events by text subtitle
> Fix title event

- modules.d.ts
- package-lock.json
- package.json
- src/app/carte-base-adresse-nationale/components/PanelDistrict/PanelDistrictMicroToponymList.tsx
- src/components/Pagination/soft-pagination.tsx
- src/components/ValidateurBAL/ValidationAccordion.tsx
- src/components/ValidateurBAL/ValidationCodeTable.tsx
Ajout d'une pagination sur les erreur du rapport du validateur
> fix: pagination accordion error validation

- public/markdown/decouvrir-la-BAN--la-base-adresse-nationale.md
- public/markdown/decouvrir-la-BAN.md
- public/markdown/la-ban/contenu-de-la-ban-intro.md
Add link on text "Licence Ouverte"
Pages : 
1) Contenu de la BAN
2) Découvrir la BAN
3) Bloc  droit info générale
> Add link for licence ouverte

- src/app/layout.tsx
Modification texte du bandeau d'information
> Changement du message d'information

- src/data/ban-events.json
> add adress_lab event

- src/app/api/certificat/[idAdresse]/components/certificat.tsx
Ajout du lieu-dit dans le document certificat
> certificat: ajout du lieu-dit

- src/app/programme-bal/page.styles.ts
- src/app/programme-bal/page.tsx
- src/components/Events/OnlineTrainingPage.tsx
- Mise à jour page programme BAL : Les images AITF et AMF vont en bas de page
- Lien vers la page des formations
- Petit texte en haut de la page des formations
> feat: update page programme bal

- src/components/PartenairesDeLaCharte/CandidacyForm/index.tsx
- Rend le champ "Lien vers la charte" facultatif pour la candidature des partenaires de la charte
> fix: partenaire de la charte link to charte nullable

- next.config.mjs
redirection des anciennes url des témoignages vers celle du blog.
#2103
> redirection des anciens temoignages vers le blog

- src/app/outils/csv/components/geocoder.tsx
Sur le lancement du géocodage,  Rétablit l'affichage 'En cours de géocodage ...'
fix #2082
> fix pending status

- src/data/ban-events.json
Modification date du reunion utilisateur pour le 29 Avril
Fix: #2118
> Maj event reunion utilisateur

- src/app/outils/csv/page.tsx
> fix filter by insee code #2116

- src/app/nous-contacter/page.tsx
Changement du bloc osmose sur la page Contactez-nous
Fix: #2129
> Changement bloc collectif utilisateurs

- src/components/PartenairesDeLaCharte/SearchPartenaire/PartenaireCard.tsx
Change le wording pour le lien vers le site des sociétés référencées dans l'annuaire
> fix: wording link for company website

- src/components/Events/OnlineTrainingPage.tsx
- Ouvre automatiquement les modals d'inscription aux formations suivant un hash passé dans l'URL
> feat: auto open event modal

- package-lock.json
- package.json
- src/components/Section/Section.tsx
- Ajoute des ids automatiquement en fonction du titre d'une section (Demande d'Olivier)
> feat: add ids to sections

- package-lock.json
- package.json
Passage de la version 5.0.0 -> 5.1.0 pour découpage administratif
Fix: #2137
> modification version decoupage administratif

- src/components/Events/EventCard.tsx
- src/types/events.types.ts
Ajoute un nouveau type de formation
> feat: add special training

- .env.default
- package-lock.json
- package.json
- src/utils/contours-communes.ts
Maj version 5.2 découpage administratif
Maj année pour variable environnement NEXT_PUBLIC_API_GEO_URL=https://geo.api.gouv.fr/2025
> Maj version 5.2 decoupage administratif

- src/app/carte-base-adresse-nationale/components/PanelAddress/PanelAddressFooter.tsx
Voir la description dans le ticket
Pour tester : 17 bis quai de Lesseps  sur Bayonne
Fix : #2159
> Modification texte certificat si manque criteres requis

- src/components/Commune/CommuneCertificationBar/index.tsx
https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/2175
> fix: hour shift on commune page

- src/app/layout.tsx
Mise en place message d'actualité
en rapport avec le ticket #2177
> Message actu pour maintenance

- src/lib/api-insee.ts
Issue : https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/2153
> fix: return empty array when commune doesnt have communes precedentes

- README.md
Reprise des modifications d'un tulisateur readme qui provoquait des erreurs CI
> Modification wording README

- src/app/blog/[slug]/components/AsideContent.tsx
Modifier le lien newsletter sur le blog.
Fix: #2228
> Modif link newsletter sur le blog

- src/app/layout.tsx
Ajout d'un bandeau de maintenance sur l'ensemble du site pour la journée du 02 Septembre
Fix: #2235
> Ajout bandeau maintenance site 02 Septembre

- src/app/donnees-personnelles/page.tsx
Suite à l'ajout de connexion par proconnect, mise à jour des données personnelles
Voici une copie d’écran des modifications : 
Fix : #2237
> Mise à jour RGPD

- src/app/layout.tsx
Suppression Bandeau de maintenance du 02 Septembre
> Suppression Bandeau de maintenance
