BaseAdresseNationale/adresse.data.gouv.fr

components/csv/csv.js, components/csv/geocoder.js, components/csv/table.js, lib/detect-encoding.js, lib/geocode/many.js, package.json, yarn.lock
Effet de bord possible : l'auto-détection étant basée sur un modèle probabiliste, il peut y avoir erreurs. On pourra rétablir le sélecteur en mode avancé.
Implémente #81
Devrait corriger #84 #62 #51
=> Amélioration de l'outil de géocodage en ligne

.circleci/config.yml, lib/geocode/many.js
Cela permet d'indiquer au navigateur quoi faire avec le fichier produit.
Permet notamment l'ouverture dans Excel.
=> Spécifie que le résultat du géocodage est au format CSV

components/bal/validateur-bal.js
Lorsqu'une URL est valide et a pu être analysé, celle-ci est encodé est ajouté à la barre d'adresse afin, par exemple, de partager le résultat.
=> Recopie de l'URL encodée dans la barre d'adresse

components/head.js
=> Améliore l'affichage sur mobile du composant en-tête

components/bases-locales/bases-adresse-locales/dataset/header.js
fix #146 Limiter la hauteur des logos
=> Limite la hauteur des logos

package.json, yarn.lock
Ajoute le support comme alias des noms de colonnes en majuscule.
=> Mise à jour de la bibliothèque @etalab/bal (0.9.0)

components/bases-locales/editor/index.js
Une erreur de variable rend l'annulation de changement d'un numéro impossible.
=> Correction de l’annulation de changement d’un numéro

components/bases-locales/validator/report/index.js, components/bases-locales/validator/report/line-value.js, components/bases-locales/validator/report/line.js, components/bases-locales/validator/report/row.js, components/bases-locales/validator/report/rows.js, package.json, yarn.lock
Affiche la valeur `rawValue` des champs inconnus. Ces champs n'étant ni "valide" ni "erronés", ils sont désormais afficher en gris afin d'être plus neutre.
Fix #165 Test du validateur BAL
=> Corrige l'affichage des champs inconnus

components/bases-locales/bases-adresse-locales/dataset/communes-preview.js, components/bases-locales/bases-adresse-locales/dataset/preview/index.js
Correctif rapide pour ne pas afficher d'erreur 500 quand le résultat d'analyse est incomplet.
=> Correctif listing des BAL

components/bases-locales/validator/index.js, components/bases-locales/validator/report/index.js, components/bases-locales/validator/report/line-value.js, components/bases-locales/validator/report/row-issues.js, components/bases-locales/validator/report/row.js, components/bases-locales/validator/report/rows.js, package.json, yarn.lock
Sépare en "erreurs" et "avertissements".
Dans les deux cas cela fait perdre la conformité, mais les avertissements n'empêchent pas le processing des données.
Pour tester il faut faire tourner sa propre instance d'API BAL (`master`) en local, et définir la variable `API_BAL_URL`
=> [BAL] Traite les résultats du validateur selon leur gravité

components/bases-locales/validator/report/index.js, components/bases-locales/validator/report/issue-rows.js, components/bases-locales/validator/report/row.js, components/bases-locales/validator/report/rows.js, components/bases-locales/validator/report/summary.js, package.json, yarn.lock
Ajoute un résumé des erreurs et avertissements du validateur.
Ce résumé a pour objectif de ne pas afficher une liste interminable de lignes comportant des anomalies car bien souvent il s'agit d'erreurs structurelle.
- Sépare les erreurs des avertissements
- Groupe les lignes par erreur/avertissement
- Indique le nombre de lignes concernées par l’erreur/avertissement
- Affiche en un clique les ou la ligne concerné
Fix #195 Résumer les erreurs structurelles du validateur
=> Résume les erreurs et avertissements du validateur

components/bases-locales/bases-adresse-locales/bal-report.js, pages/bases-locales/datasets/dataset/report.js
Sur la page du rapport d'erreur, c'est le nom du producteur qui est affiché, et non le nom de la BAL.
=> Corrige affichage du nom de la BAL

lib/geojson.js
La couleur des numéros dépend du code de la voie à laquelle ils appartiennent.
=> Correction de la couleur de numéro

components/bases-locales/editor/edit-bal/init-base.js, components/bases-locales/editor/edit-bal/search-communes.js
Jusqu'à maintenant il pouvait être impossible de sélectionner une commune avec de nombreux homonyme.
Exemple ici je cherche à sélectionner Saint-Just, dans le département du Cher :
Cette PR augmente le nombre de résultats potentiels à 8 (au lieu de 5) et permet de préciser le code du département.
Exemple avec 8 résultats :
Exemple avec un code département :
=> Amélioration du sélecteur de commune

lib/bal/item.js, lib/geojson.js
La réutilisation des fonctions de conversion en geojson n'était pas compatible entre les deux modèles utilisés pour `/explore` et `/bases-locales`.
Cette PR propose une correction en attendant la convergence des modèles.
=> Corrige les problèmes de modèle Adresse

components/bases-locales/editor/uploader.js
Jusqu'à maintenant seul les erreurs de taille de fichier et d'extension était retourné à l'utilisateur. Le rapport de validation n'était jamais affiché.
=> Corrige l'affichage du rapport d'erreur d'un fichier BAL invalide

components/faq/index.js, components/tools.js, pages/api.js, pages/cgu.js, pages/donnees-nationales.js
- Réduit l'espace entre les sections de la FAQ
- La taille des `Tool` est la même
-  Utilisation de la `class row` de template.data.gouv.fr dans les CGU
- Affiche le nom de la licence dans l'avertissement concernant l'homologation du produit gratuit issu de la BAN
- Les balises `code` s'élargissent au maximum dans la documentation de l'api
- La couleur des liens hypertexte, dans la documentation de l'api, ont été changés pour être plus lisible
=> Correction mineur d'affichage

components/map/index.js, components/mapbox/map.js
Le composant `Map` ajoute par défaut les contrôles de zoom sur les cartes.
Cette PR apporte également des corrections à l'affichage de la carte interactive. En effet, sur mobile la barre de recherche pouvez être cachée par l'adresse et le contrôleur de la carte caché par la barre de recherche.
=> Ajout des contrôles de zoom sur les cartes 

components/mapbox/map.js
Lorsque les informations à afficher sont trop grande pour la carte, celle-ci entrées en collision avec le changement de style de la carte.
=> Corrige l'affichage des informations de la carte

pages/_app.js
L'utilisation du composant <Container> dans `./pages/_app.js` est désormais déprécié.
Cf https://github.com/zeit/next.js/blob/master/errors/app-container-deprecated.md
=> Suppression de composant <Container> de next

components/mapbox/layers/positions.js
Ajout de d'encrage variable pour les labels permettant ainsi à Mapbox d'éviter les collisions quand c'est possible.
Fix #454
=> Correction de la superposition des labels

components/explorer/commune/codes.js, components/explorer/commune/head.js, components/explorer/commune/index.js, components/explorer/commune/metrics.js, components/explorer/table-list/filters/checkbox-input.js, components/explorer/table-list/filters/tags-input.js, components/explorer/voie/head.js
La classe **RadioInput** devient **CheckboxInput**.
Les inputs "_radio_" sont remplacés par des "_checkbox_".
Le fichier `components/explorer/tablea-list/filters/radio-input.js` devient `components/explorer/tablea-list/filters/checkbox-input.js`.
=> replace radio-input by checkbox-input

components/explorer/table-list/table-control.js
Le bouton `Réduire` était affiché à la place de `Tout Afficher`:
=> Correction d'un bug d'affichage

components/mapbox/layers/numeros.js, components/mapbox/map.js
- Correction de l'affichage de numéros partageant la même position
- Changement du visuel des Numéros
- Ajout du switch pour changer le style de la carte (Vectoriel / Satellite) 
Avant :
Après :
=> Modification du visuel de Numéro & Ajout du switch-map

components/open-licence-ribbon.js
=> Ajout de padding et media-query sur le bandeau Licence Libre

components/bases-locales/bal-cover-map.js
La Base Adresse Nationale étant passée sous Licence Ouverte, l'incorporation des BAL dans celle-ci, quelles que soient leurs licences sources est facilitée.
Il n'est plus nécessaire de conduire la politique de convergence à ce stade.
Avant
Après
=> Retrait de la colorisation différenciée des BAL selon la licence

components/bases-locales/bases-adresse-locales/summary.js, components/bases-locales/index.js, components/button-link.js, pages/contribuer.js
- Fix issue #572 
- ajout d'un boolean `isExternal` dans le composant `<ButtonLink>` pour les liens externes
- ajout de la props `isExternal` dans les liens externes des fichiers :
- `components/bases-locales/index.js`
- `/components/bases-locales/bases-adresses-locales/dataset/index.js`
- `pages/contribuer.js`
=> Ajout de isExternal pour les liens externes

components/search-input/index.js
Fix #579 
- Augmentation du `z-index` dans le composant `<SearchInput />`
Les résultats sont maintenant affichés au dessus du contrôle de zoom de la carte.
=> Correction d'affichage des résultats de recherche dans /explore

components/bases-locales/bases-adresse-locales/dataset/index.js
Le lien de téléchargement utilise le composant `<ButtonLink>` mais n'avait pas la propriété `isExternal`.
Ce qui générait l'erreur : `Unhandled Rejection (Error): Invalid href passed to router:`
- Fichier concerné : `components/bases-locales/bases-adresse-locales/dataset/index.js`
- Capture du bouton :
=> Ajout de isExternal au lien de téléchargement dans la BAL

components/explorer/voie/index.js, components/explorer/voie/sources-voie.js
=> Ajout de la source des libellés de voie dans /explore 

components/explorer/commune/voies-commune.js, pages/explore/commune.js
Sur la page `explore/commune/voie` la barre d'adresse affichait `undefined`
- **Exemple**
https://adresse.data.gouv.fr/explore/commune/undefined/voie/57463_2995
- **Capture d'écran**
=> [Explore/Commune/Voie] 'undefined' dans la barre d'adresse 

components/explorer/explore-search.js
Ces villes ne sont pas gérées et renvoi vers une erreur `404`.
=> Retire Paris, Marseille et Lyon de la barre de recherche

pages/faq.js
=> Dans la FAQ le lien vers le guide est absent

components/explorer/voie/map-container.js
Issue #712 
Correction de l'erreur qui ajoutait "null" aux numéros sans suffixe au clique depuis la carte
- Modification de la condition qui renvoie `null` au lieu de la string `"null"` quand il n'y a pas de suffixe
=> Correction du bug de redirection à la sélection d’un numéro depuis explore

components/mapbox/hooks/sources.js, lib/geojson.js
Issues #713 et #577
- Suppression de la propriété id de la méthode `numeroToFeature `de `lib/geojson`
- Remplacement du type "Point" par "Feature" dans `lib/geojson`
- Ajout de la propriété `generateId` à la source liée aux numéros dans le hook `useSources`
*edit*
- Ajout de la propriété `generateId` à la source liée aux positions dans le hook `useSources`
=> Correction de l'erreur d'identifiant de "feature" renvoyée par MapBoxGL

components/bases-locales/bases-adresse-locales/dataset/header.js
- Ajout de la propriété `objectFit ` avec la valeur `contain` dans le composant `Image`
*captures :*
- avant
- après 
*https://adresse.data.gouv.fr/bases-locales/jeux-de-donnees/5fb62ef835244cf29665cca7*
=> Correction de la taille du logo des BAL

components/bases-locales/bases-adresse-locales/index.js, pages/bases-locales/publication.js, pages/contact.js, pages/faq.js, pages/gerer-mes-adresses.js
Beaucoup d'utilisateurs ne se rendent pas compte qu'ils quittent adresse.data.gouv.fr lorsqu'ils cliquent sur un lien menant sur http://mes-adresses.data.gouv.fr/. Cela à pour effet qu'ils ne savent pas comment retourner sur l'édition de leur BAL et pour y parvenir ils refont tout le parcours depuis la page d'accueil de http://adresses.data.gouv.fr/
Afin de faire comprendre à l'utilisateur que la création de leur BAL ne se passe pas sur adresse, cette PR propose d'ouvrir liens important menant à http://mes-adresses.data.gouv.fr/ dans un autre onglet.
=> Ouverture d'une nouvelle page sur les lien vers Mes Adresses

components/base-adresse-nationale/numero/index.js
- Ajout de 3 champs supplémentaires sur la page `numero` : 
- Libellé d’acheminement
- Code postal
- Clé d’interopérabilité
*capture* :
=> Ajout de champs supplémentaires sur la page numero

components/mapbox/ban-map/index.js, components/mapbox/center-control.js, package.json, yarn.lock
- Désactivation du bouton "recentrer" :
- quand les propriétés de l'adresse sélectionnée ne sont pas visibles
- quand aucune adresse n'est sélectionnée
- Ajout d'un `padding` au recentrage. Permet d'être au même `bound` que lors de la sélection d'une adresse.
*capture vidéo*
https://user-images.githubusercontent.com/45098730/104718494-3e938e80-572b-11eb-9f86-8855974c0314.mp4
=> Désactivation du bouton "recentrer" en fonction du contexte

components/bases-locales/publication/published.js, pages/bases-locales/publication.js
Après la publication d'une Base Adresse Locale, l'utilisateur se retrouvait dans une page "impasse" confirmant simplement la publication de sa Base Adresse Locale. Cette page assez pauvre en terme de retour pour l'utilisateur est maintenant utilisée pour informer l'utilisateur sur les conséquences de sa publication mais aussi le guide et l'encourager à continuer l'adressage sur cette même Base Adresse Locale.
=> Information supplémentaire après la publication

components/base-adresse-nationale/addresses-list.js, components/base-adresse-nationale/commune/index.js
*avant*
*après*
_____
*edit commit [7d155b2 (Remove search bar when no address is available)](https://github.com/etalab/adresse.data.gouv.fr/commit/7d155b22993f155ae62bb7f285e9a97cf60ee99d)*
=> Correction d'une coquille concernant l'affichage du nombre de voie et de lieu-dit

components/base-adresse-nationale/numero/index.js, components/base-adresse-nationale/voie/numero.js, components/mapbox/ban-map/popups.js
Correspond au champ `lieudit_complement_nom` du format BAL 1.2.
L'information est affiché dans le listing des numéros :
Dans le panneau d'infos du numéro :
Et dans la popup du numéro sur la carte :
Un peu de CSS ne serait pas de refus ;)
=> Affiche le lieu-dit / complément de nom

components/bases-locales/index.js
This PR just add an ID to this section : 
Allows to made a link to it on the dashboard page on mes-adresses
**PR related to this one https://github.com/etalab/editeur-bal/pull/318**
=> Add an id to map section in bases-locales

components/bases-locales/charte/partner.js, components/temoignage.js
- Supprimer les div servant de séparateurs et remplacer par des border-bottom
- Utiliser les couleurs établies dans la charte graphique
=> Utiliser les couleurs de la charte graphique et modifications bordures

components/base-adresse-nationale/voie/index.js, components/mapbox/ban-map/index.js, pages/base-adresse-nationale.js
Certaines adresses comme https://adresse.data.gouv.fr/base-adresse-nationale/05001#11.07/44.7721/6.9715 provoque une `erreur 500` car celles-ci ne possède pas de position à afficher sur la carte.
- Conditionne le calcule du fitbound à la présence de la valeur `displayBBox`
- Affiche un message d'avertissement afin de renseigné l'utilisateur sur l'absence de position de l'adresse sélectionnée
=> Correction erreur 500 quand une adresse n'a pas de position

components/bases-locales/charte/search.js, partners.json
- Rendre les hashtags plus généralisés
- Changement du label de la barre de recherche
- Trier les partenaires trouvé de manière à ce que ceux dont le périmètre d'action est élargi à la France entière (ex: Sogefi) apparaissent en dernier.
- Suppression d'un coquille gênant la génération de hashtags
=> Changements mineurs sur la barre de recherche des partenaires

partners.json
Correction du lien vers le site de la Communauté de Communes du Pont du Gard
- `https://www.atd16.fr` remplacé par `http://www.cc-pontdugard.fr`
=> Correction de la fiche partenaire de la Communauté de Communes du Pont du Gard

partners.json
- `https://www.yonne.fr/Territoire/Amenagement-numerique` remplacé par
- `https://www.yonne.fr/Territoire/Amenagement-numerique/Fiabilisation-de-l-adressage`
=> Mise à jour de la fiche partenaire du département de l'Yonne

components/ban-search.js, components/search-input/render-addok.js, lib/api-adresse.js
Il arrive que certains utilisateurs ne trouvent pas l'adresse qu'ils recherchent à cause de la limitation à 5 résultats.
Augmenter à 7 le nombre de résultat afin d'augmenter les chances de satisfaire la demande utilisateur tout en évitant des requêtes trop importante et la surcharge visuel que pourrait résulter d'un trop grand nombre de résultats.
- *avant*
- *après*
- *edit : 7 résultats*
=> Extension de la limite de la recherche à 7 résultats

components/base-adresse-nationale/addresses-list.js, components/base-adresse-nationale/commune/index.js
resolves #753
- Affiche `Aucun lieu-dit` quand il n'y en a pas
*edit commit [34da968](https://github.com/etalab/adresse.data.gouv.fr/pull/820/commits/34da968a8cc55790628117068120d366d3577635)*
=> Changement du titre de la liste des lieux-dits quand celle-ci est vide

components/bases-locales/validator/report/summary/issues-sumup.js
resolves #779 
*avant*
*après*
____
*edit 09/06 (commit [cb0533a](https://github.com/etalab/adresse.data.gouv.fr/pull/824/commits/cb0533a5703184e60167e3992212325b6976999a))*
=> Ajout d'informations sur le nombre de lignes concernées par les erreurs/avertissements dans le validateur

package.json, yarn.lock
Mise à jour vers la dernière version de [react-dropzone](https://react-dropzone.js.org/) actuellement 11.3.2.
Lien vers la dernière version : 
[https://github.com/react-dropzone/react-dropzone/releases/tag/v11.3.2](https://github.com/react-dropzone/react-dropzone/releases/tag/v11.3.2)
Fix #724
=> Mise à jour de la librairie react-dropzone en version 11.3.2

components/doc-download.js
=> Suppression de l'espace blanc en bas de l'image des guides

components/base-adresse-nationale/certification.js
- Fix typo : `Certification.propTypes` -> `Certification.defaultProps`
*avant*
*après*
=> Corrige la taille par défaut des icônes du composant Certification

components/base-adresse-nationale/commune/index.js, components/base-adresse-nationale/numero/index.js, components/mapbox/ban-map/layers.js
Avant cette PR la certification est globale à la commune, et dépend de si les adresses proviennent d'une BAL.
Cette PR ajoute la certification à l'adresse, en particulier pour les adresses issues du Guichet Adresse.
=> Implémente la certification à l'adresse

components/mapbox/ban-map/layers.js, components/mapbox/ban-map/popups.js
Nouvelles couleurs plus lisibles pour les différentes sources
Affichage de la source de l'adresse plutôt que la source de la position et du nom.
=> Clarification des sources dans l'explorateur BAN

components/base-adresse-nationale/commune/index.js
Actuellement si une commune n'a aucune adresse, celle-ci est indiquée comme "certifiée" car le nombre d'adresse est égale au nombre d'adresse certifiée (qui est de zéro)
=> Correction de l'affichage du logo "certifié" pour les communes sans adresse

pages/bases-locales/publication.js
Correction du problème d'affichage du message d'erreur à la publication d'un base adresse locale.
Lors de la publication, le message d'erreur n'affichait pas les informations techniques.
=> Corrige le problème d'affichage du message d'erreur à la publication

components/bases-locales/publication/code-authentification.js, components/bases-locales/publication/manage-file.js, lib/bal/api.js, pages/bases-locales/publication.js
Le support a remonté des erreurs lors de tentative de publication de BAL via un fichier CSV. Cette erreur "vide" bloque la publication.
Il s'est avéré que le dépôt d'un fichier CSV provoquait la création de plusieurs `submissions` et il pouvait arrivé qu'un mauvais `submissionId` soit envoyé lors de la demande de publication. De plus, les messages ne remonte pas correctement à l'utilisateur car mal récupérer par `HttpError`.
- L'upload du CSV ne se fait plus grâce à la `state` `file` mais directement après validation du fichier, évitant ainsi que la méthode soit appelée plusieurs fois.
- `HttpError` a été remplacé afin de pouvoir récupérer le message de l'api depuis le `body` de la réponse.
- La récupération du message d'erreur pour la validation du code d'authentification a été corrigé. …
=> Corrige la création de submission en double lors d'un dépôt de fichier CSV

components/mapbox/map.js
Suppression du proxy Etalab.
Il n'est plus nécessaire.
Avantages :
- plus besoin d'espace de stockage pour le cache
- un composant en moins à maintenir
Inconvénient :
- On perd l'HTTP/2 pour le moment
=> Change l'URL du fond de carte photos aériennes IGN

components/base-adresse-nationale/commune/index.js
Actuellement si une commune possède au moins une adresse certifiée alors celle-ci affiche que les adresses sont en cours de certification alors que ce statut est réservé aux Bases Adresses Locales.
Affichage de l'icône "certifié" uniquement si la commune est issue d'une BAL.
=> Correction du code couleur affiché pour les BAL

components/base-adresse-nationale/numero/index.js, components/base-adresse-nationale/voie/numero.js, components/mapbox/ban-map/index.js, components/mapbox/ban-map/layers.js
La dernière évolution (#854) permettant de connaitre la certification à l'adresse a introduit un nouveau pictogramme GRIS indiquant lorsqu'une commune issue d'une BAL n'avait pas encore certifiée toutes ces adresses.
Il a été décidé de ne pas répercuter ce pictogramme aux adresses pour rester simple (adresse certifiée ou non). Cependant, ces adresse affiche aujourd'hui un pictogramme ORANGE, hors certaines communes ont belle et bien vérifiée ces adresses mais n'ont pas encore validée cette certification depuis l'ajout de la fonctionnalité. 
Cette PR propose d'étendre ce pictogramme GRIS `Certification en cours par la commune` aux adresses. Il sera donc affiché uniquement aux adresses non certifiées issue d'une BAL.
=> Indiquer une certification en cours au niveau de l'adresse

partners.json
Modification du lien du partenaire "la Communauté de Communes du Pont du Gard"
Fix #860
=> Modification d'un lien partenaire de la charte

components/bases-locales/bases-adresse-locales/summary.js
Cette PR remplace la ligne `licence` par le nombre de communes couvertes par la Base Adresse Locale.
Avant : 
Après :
Fix #885
=> Affiche le nombre de communes couvertes par la Base Adresse Locale dans le résumé

components/bases-locales/charte/partner.js, partners.json
fix #892
Décalage de l'affichage des partenaires lorsque le titre est sur deux lignes ou plus. Les conteneurs des partenaires doivent être de hauteur et largeur identique.
=> Décalage affichage des partenaires

lib/bal/api.js, pages/bases-locales/publication.js
Si une BAL invalide est soumise via le paramètre `url` de la `/bases-locales/publication`, une erreur générique est affichée à l'utilisateur : `Une erreur est survenue lors de la récupération du fichier`.
Cependant ce message d'erreur est immédiatement effacé par un `useEffect` permettant de réinitialisé le message d'erreur si l'étape du formulaire venait à changer. Dans notre cas, c'est dès le premier rendu que cette valeur `step` change et donc passe la valeur `error` à `null`.
De plus, l'en-tête permettant aux utilisateurs venant de Mes Adresses de pouvoir y retourner via un lien n'est pas affiché car la variable `isRedirected` n'est pas encore renseigné au moment où l'erreur est capturée.
- Amélioration du message d'erreur affiché à l'utilisateur en cas d'échec de la soumission d'une …
=> Corrections et améliorations de l'expérience utilisateur lors de la publication

package.json, pages/_app.js, pages/_document.js, yarn.lock
La feuille de style https://template.data.gouv.fr est désormais chargée via `node_modules` et `next`.
=> Suppression de la dépendance à unpkg.com

components/bases-locales/index.js, components/map-bal-section.js, pages/bases-locales.js, pages/index.js
Ajout de la même section présente dans la homepage afin que l'utilisateur puisse retrouver les infos pertinentes également dans la page /bases-locales
=> Section vers la carte de déploiement de la bal dans la page bal

.env.sample, lib/api-ban.js, lib/bal/api.js, pages/bases-locales.js, pages/deploiement-bal.js, pages/index.js
L'ancienne API `/stats` n'était plus utilisée (service `backend`) mais le code toujours présent.
J'ai aussi déplacé le nouvel appel `/stats` sur `plateforme.adresse.data.gouv.fr` au bon endroit puisque ce n'est pas un appel BAL.
=> Légère réorganisation du code API/Stats

components/bases-locales/index.js, lib/bal/api.js, pages/bases-locales.js, pages/bases-locales/datasets.js
Utilise les nouveaux paramètres `noContour` et `sample` pour ne retourner de l'API que ce qui est nécessaire à l'affiche.
Boost conséquent des performances sur les deux pages concernées.
=> Optimisation des appels au listing des BAL

components/doughnut-counter.js, layouts/base-adresse-nationale.js
Depuis la mise à jour du logo dans le header, celui ci étant plus grand que le précédent logo, la cartes de la BAN et du déploiement ont été décalées et débordent légèrement dans le bas de la fenêtre.
Cette PR propose d'ajuster les valeurs de taille pour éviter d'avoir un débordement et conserver un comportement sans barre de défilement.
=> Corrige la taille des cartes après la modification de la taille du header

pages/contribuer.js
Certains utilisateurs contactent le support pour des problèmes d’adresse. 
Cette PR propose d’ajouter le composant permettant la recherche du contact d’une commune pour que ces utilisateurs se dirigent directement vers leur mairie.
=> Ajout du composant de recherche du contact d’une commune à la page contribuer

package.json, yarn.lock
Mise à jour de la librairie `etalab/bal` vers la version 1.8.0
[Changelog](https://github.com/BaseAdresseNationale/bal/releases/tag/v1.8.0)
Fix #920
=> Mise à jour de la librairie etalab/bal

components/frise.js
- Conflit de date pour l'affichage de l'hiver résolu => comparer avec le début des dates du printemps de l'année suivant.
- Correction des dates de solstice
=> Correction sélections des dates de solstices 

pages/index.js
Si l'appel à https://plateforme.adresse.data.gouv.fr venait à échouer, aucune capture d'erreur ne serait là pour éviter une erreur 500 lors du chargement de le page d'accueil.
Ajoute un `try/catch` lors de la récupération des statistiques BAN lors du chargement de la page d'accueil.
=> Sécurise la récupération des statistiques BAN

pages/index.js
Corrige une faute de frappe dans le `getInitialProps` de la page d’accueil empéchant l’affichage du composant `MapBalSection`
=> Corrige l’affichage du déploiement des Bases Adresses Locales sur la page d'accueil

components/doughnut-counter.js, pages/deploiement-bal.js
=> Adapter l'affichage des statistiques du déploiement des BAL aux grands écrans

pages/donnees-nationales.js
Close #991
Remplacer la balise parente `<p>` de la liste par une `<div>`
Résout l'erreur : `Warning: validateDOMNesting(...): <ul> cannot appear as a descendant of <p>.`
=> Corriger l'erreur de DOM nesting

components/fantoir/body-list-fantoir.js, components/fantoir/header-list-fantoir.js, components/fantoir/voie-information.js, lib/api-ban.js, lib/api-geo.js, pages/fantoir/departement/[departement]/commune/[commune]/index.js, pages/fantoir/departement/[departement]/index.js, pages/fantoir/index.js, pages/tools.js
Cette PR propose l'ajout d’une page permettant de naviguer dans les données FANTOIR.
Captures :
=> Ajout d’une page pour naviguer dans les données FANTOIR

pages/contribuer.js
`En attendant, contactez votre mairie ou votre EPCI, et parlez-leur de nous !`
devient : 
`En attendant, contactez votre mairie, et parlez-leur de nous !`
=> Suppression des EPCI dans la section de contact mairie

components/frise.js
=> Suppression affichage du nom du svg de la frise lors d'un hover

components/bases-locales/publication/manage-file.js, components/bases-locales/validator/index.js, components/bases-locales/validator/report/summary/index.js, components/bases-locales/validator/report/summary/issue-dialog.js, components/bases-locales/validator/report/summary/issue-rows.js, components/bases-locales/validator/report/summary/issues-sumup.js, components/bases-locales/validator/report/summary/line-value.js, components/bases-locales/validator/report/summary/line.js, components/bases-locales/validator/report/summary/row-issues.js, components/bases-locales/validator/report/summary/row.js, package.json, pages/contribuer.js, yarn.lock
Depuis la version `2.0.0` le validateur est strict par défaut. Cette PR rétablit un fonctionnement souple pour afficher plus d'erreurs.
La version `2.1.0` introduit par ailleurs de nouvelles règles classées "informations" que ne sont pas nécessairement des problèmes.
Les niveaux sont donc désormais :
- `error` : erreur qui empêche la prise en compte de la ligne
- `warning` : avertissement qui indique un écart avec la spécification ou une anomalie non bloquante. Dans certains cas la donnée litigieuse est corrigée, dans d'autres elle est ignorée.
- `info` : autre information remontée par le validateur
=> Mise à jour du validateur BAL

pages/gerer-mes-adresses.js
Le site ne comprenait pas d'accès au formulaire de dépôt. L'utilisateur devait soit passer pas la documentation, soit connaitre l'url pour y accéder.
Cette PR ajoute une section donnant accès au formulaire de dépôt depuis la page `/gerer-mes-adresses`
=> Ajout d'un point d'entrée pour le formulaire de dépôt

pages/contribuer.js
Close #1026
Dans la page `/contribuer`
Permet de pointer vers les sections : 
- En tant que commune
- En tant que citoyen
- En tant qu’utilisateur des données
=> Ajout ancres vers les contributeurs 

package.json, yarn.lock
Ce dernier est désormais aligné avec le Code Officiel Géographique 2022
=> Mise à jour du validateur BAL @etalab/bal (2.2.0)

pages/commune/[codeCommune].js
Close #1054
Conditionner l'appel de recherche de la révision courante dans le cas où la commune suivant son type de composition.
=> Correction de l'erreur 404

pages/evenements.js
Utilisation d'un format standard de date afin de garantir un traitement fonctionnel et universel à chaque navigateur.
[Documentation date.parse()](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Date/parse#description)
=> Correction format date sous Safari et IE

components/evenement/event-banner.js, lib/date.js, pages/evenements.js, pages/index.js
La version précédente de la bannière en page d'accueil n'affichait qu'en "dur", le prochain AdresseLab.
Suite à l'ajout de la page évènements, il est plus pertinent d'afficher de manière dynamique les évènements à venir et de fournir un accès rapide à l'utilisateur concernant les détails des évents.
- Affichage des trois évènements prévus, du premier à venir au dernier, via un système de slides.
- Changement de slide via un timer et un système de contrôle manuel.
- Indique le nom de l'évènement, la date. Affiche la modale avec la totalité des informations lors du click sur le nom de l'évènement.
https://user-images.githubusercontent.com/66621960/156160700-a70c9e91-5714-43c3-8c5d-c24b4fa7550c.mov
=> Amélioration de la bannière évènements page d'accueil

events.json
Close #1086
Le 26 étant férié, la date change pour le 20 mai
=> Changer la date du webinaire du 26 mai

components/bases-locales/charte/partners-searchbar.js, components/bases-locales/charte/partners.js, components/bases-locales/index.js, pages/bases-locales/charte.js, partners.json
Afin d'accueillir le nouveau type de partenaires de la Charte (communes), une réorganisation du JSON contenant les partenaires permet de faciliter le développement en proposant un code plus lisible et mieux organisé. 
Il est à présent possible de distinguer les epci, entreprises et communes disposant chacun de leur tableau avec la liste des partenaires correspondants.
=> Amélioration du modèle json pour les partenaires

components/post.js
Les articles en provenance du blog Ghost utilisent certaines classes CSS spéciales qui n’étaient pas prises en charge, créant un affichage chaotique.
Cette PR propose la prise en charge des blocs Ghost principaux : 
- Bookmark (MAJ)
- Image
- Gallery
- HTML
- Markdown
- Divider
- Button
- Toggle
- Header
- File
- Video
- Audio 
- Callout
- Product
=> Prise en charge du CSS des blocs du blog Ghost

components/blog-card.js, components/post.js, lib/blog.js, pages/blog/index.js
**_Cette PR propose d’afficher le nom de l’auteur de l'article et quelques modifications visuelles._**
Le nom de la personne ayant rédigé l'article est maintenant affiché sur la page `/blog` ainsi que sur la page affichant l’article.
- Le nom de l’auteur ainsi que la date de publication de l’article sont maintenant affichés en dessous de la `feature_image`
- La hauteur de la `feature_image` a été réduite pour plus de lisibilité de l’article
- La taille du titre a été réduite
=> Blog: Affichage de l’auteur et optimisations visuelles

pages/index.js
Cette PR propose de modifier le lien du fichier `commune-operateurs-obligations-adresse.pdf` vers sa version v2.0
Fix #1101
=> Mise à jour du fichier PDF en page d’accueil

partners.json
Le partenaire `Anne Légaut` a été dupliqué par erreur lors de la réorganisation du fichier JSON partenaires #1100 .
=> Supprime un partenaire dupliqué par erreur

partners.json
Close #1107
Les partenaires ne nécessitent plus d'afficher les tags "animation" et "diffusion" qui sont donc supprimés ici.
Ils ne sont plus sélectionnables dans la section de recherche ni affichés ni dans la section informations du partenaire.
=> Suppression de tags inutiles pour les partenaires

components/evenement/event-modal.js, events.json
- Le webinaire du 14 avril avait toujours le lien d'inscription à l'évènement disponible alors que les inscriptions sont closes.
- Le lien d'inscription au webinaire de 5 mai n'était pas entré au bon endroit dans le json.
=> Correction des liens d'inscription aux webinaires

pages/blog/[slug].js
Close #1097
La plupart des alertes pour les variables en camel case ont été traitées dans ce [commit ](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1087/commits/89a90b86bd65071cc6f13b19df3be4759fae9f94) fait par Guillaume sur cette [PR](https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/pull/1087) (mergée à ce jour).
Or, un avertissement a été oublié et est donc corrigé ici
=> Avertissement XO concernant les variables en camel case oubliées

components/bases-locales/charte/search-partners-results.js
Close #1110
Le message invitant à se référencer en tant que partenaire de la Charte ne s'affichait que si aucun partenaire n'était trouvé dans sa catégorie (communes, organismes ou sociétés).
Cette section avec un bouton contact est à présent visible par défaut à l'affichage des résultats de la recherche.
=> Encourager les communes à être référencée comme partenaire

components/base-adresse-nationale/numero/index.js
Des utilisateurs ont découvert que lorsque l’on clique sur certains numéros dans [l’explorateur BAN](https://adresse.data.gouv.fr/base-adresse-nationale/05085_0160#16.51/44.9298/6.718), celui-ci renvoi une erreur 500.
Le problème vient de la propriété `positionType` qui est parfois `null`.
Cette PR propose d’ajouter une condition qui vérifie si la propriété `positionType` existe.
Dans le cas où elle n’existe pas, cette propriété sera définie comme "(Type : ) Inconnu".
=> Corrige les erreurs 500 dans l’explorateur BAN

partners.json
Cette PR corrige la taille du logo de la commune partenaire Égliseneuve afin d'éviter les problèmes d'affichage avant le wrap des cartes partenaires sur la page [/bases-locales](http://localhost:3000/bases-locales) 
Close #1138
=> Résolution problème d'affichage du partenaire Égliseneuve

pages/bases-locales/charte/communes.js, partners.json
Suite au constat d'un oubli dans le json des partenaires (`codeRegion` dans la commune de Castillon-Savès), un bug a également été décelé.
À savoir que lorsqu'un département contient plus d'une commune partenaire, celui-ci s'affiche autant de fois qu'il a de communes.
Cette PR ajoute donc le codeRegion oublié et corrige dans la foulée le bug de duplicata de département.
Close #1158
=> Fix des duplicatas concernant les départements avec des partenaires

partners.json
`Communes concernées : 17 communes des communautés de communes de l’Île d’Oléron et du Bassin de Marennes (département 17, Charente maritime)` 
**devient** 
`Communes concernées : 14 communes des communautés de communes de l’Île d’Oléron et du Bassin de Marennes (département 17, Charente maritime)`
Close  #1143
=> Modification wording du partenaire Pôle Marennes Oléron

components/doc-download.js, pages/ressources.js
Dans la page `/ressources`, le guides de mes adresses et le guide des bonnes pratiques de l'adressage disposent maintenant de la version et la date de mise à jour du document directement sous la preview du pdf.
=> Affichage de la version du pdf 

components/base-adresse-nationale/commune/index.js, components/base-adresse-nationale/explorer.js, components/base-adresse-nationale/numero/index.js, components/base-adresse-nationale/region-infos.js, components/base-adresse-nationale/voie/index.js, components/commune/bal-state.js, lib/api-etablissements-public.js, lib/ban.js, pages/commune/[codeCommune].js
Cette PR propose un fix à l'issue #1163
**Les problèmes** : 
- L'accès à la page `/commune/<codecommune>` d'une commune des COM mène à une erreur `500`.
- Une erreur d'affichage de l'adresse se produit également sur l'explorateur.
Ces erreurs sont dûes à certaines informations manquantes chez les COM (infos de la mairie, nom/code region/departement) qui mènent soit à une erreur au chargement de la page faute d'existence des données, soit à un souci d'affichage.
**Résolution** :
- Retourner `null` si les informations ne sont pas présentes dans un `getInitialProps` afin d'éviter l'erreur `500` au retour des props.
- Conditionner l'affichage suivant si l'adresse est une COM ou non
Close #1163
=> Résolution problème affichage adresse des COM

pages/ressources.js
Certains sites placent le lien vers les guides en PDF et ces liens changent à chaque nouvelle version.
Des sites de partenaires de la charte et autres institutions renvoient actuellement vers les versions obsolètes du Guide de l'éditeur et du Guide des bonnes pratiques.
Cette PR utilise les liens symboliques qui pointe vers la dernière version disponible des guides afin de pouvoir fournir aux ré-utilisateurs un URL pérenne.
Fix #1171
=> Utilisation de lien symbolique pour les guides

components/footer.js, pages/api-doc/index.js
Suite à la mise en place de la page [status.adresse.data.gouv.fr](https://status.adresse.data.gouv.fr/), cette PR permet de référencer cette dernière sur la page `/api-doc` et d'ajouter un point d'entrée au niveau du `footer`.
Close #1165
=> Référence de la page status.adresse.data.gouv.fr

components/frise.js
Les couleurs étaient aux couleurs de l'hiver en plein été.
L'algorithme de détection de la saison actuelle a été modifié.
=> Correction du bug choix de saison pour la bannière

components/bases-locales/charte/partner.js, components/mairie/mairie-contact.js, public/images/icons/scarf.svg
Le design des cartes infos des communes partenaires présentaient un design très peu harmonieux et est donc entièrement refait.
Le choix de la petite icône de mairie à côté du nom permet de repérer immédiatement le status de ce partenaire.
=> Amélioration design carte infos des communes partenaires

components/mairie/mairie-contact.js
Corrige l'erreur 500 sur la page commune, occasionnée à l'ouverture de la modale contenant les infos de la mairie lorsque la `clef/valeur` email n'existe pas.
https://user-images.githubusercontent.com/66621960/177182966-1312fe01-86cf-4489-bc0f-43fdf07fc944.mp4
=> Correction erreur 500 contact mairie

partners.json
`https://www.saint-quentin-en-yvelines.fr/fr` devient `https://www.saint-quentin-en-yvelines.fr/fr/les-bases-adresse-de-sqy` à la demande de la Communauté d’agglomération de Saint-Quentin-en-Yvelines.
Close  #1247
=> Changement de l'url vers la Communauté d’agglomération de Saint-Quentin-en-Yvelines

components/donnees-nationales/intro.js
Mise à jour de l’encart "Caractéristiques" de la page `/donnees-nationales`
Fix #1266 
Capture :
=> Mise à jour du contenu de Données Nationales

pages/donnees-nationales.js
- Ajout d’un lien vers les tutoriels dans la partie services cartographiques sur la page "Données nationales"
- Restaure le titre "Format MVT"
Capture : 
Fix #1266
=> Ajout d’un lien vers les tutoriels SIG

components/commune-id-card.js
Le texte n'étant pas centré, lorsque certain nom de région ou de département se mettent à la ligne, le design n'est plus harmonieux. 
---------------------
=> Centrer le texte sur la carte d'identité de la commune

pages/donnees-nationales.js
Cette PR propose une modification de l’affichage des cartes de téléchargement des données sur la page `/donnees-nationales`
Captures : 
[#7](https://github.com/BaseAdresseNationale/ban-bal/issues/7)
=> Modification des cartes "Télécharger les données" de la page /donnees-nationales

components/mairie/mairie-schedules.js
Les horaires des mairies affichées par le composant `<CommuneSchedules />` étaient erronées, car les horaires à la demi-heure sont arrondis à l'heure supérieur.
Solution : Utiliser des fonctions de traitement de string au lieu de passer par la création d'un objet Date. La fonction `getHours()` devient plus facilement compréhensible à la lecture et plus facile à manipuler.
------------------------------------
Close #1286
=> Corriger l'affichage des horaires des mairies

components/evenement/event-modal.js, events.json
Cette PR apporte 3 modifications concernant les évènements autour de l'adresse.
1. Faire en sorte que les inscriptions aux Événements Partenaires soient toujours ouverte afin d'afficher les instructions. Tous les partenaires sont inscrit par défaut, il n'était donc pas nécessaire de "fermer" les inscriptions.
2. Certains des évènements `Événement Partenaire de la Charte de la Base Adresse Locale` avait un titre plus court (`Événement Partenaire de la Charte`)
3. Les media query permettant d'assurer la version mobile de la modale a été allégée. Les éléments sont maintenant alignés sur la gauche, ce qui est plus cohérent avec la version desktop.
--------------------------------------
=> Corrections mineurs sur les cartes évènements

components/bases-locales/charte/dropdown.js
Ajout d'une prop oubliée permettant d'afficher la carte de la région sur 100% de la largeur.
Close #1308
=> Correction CSS cartes communes partenaires

components/base-adresse-nationale/positions-types.js, components/maplibre/ban-map/index.js, lib/ban.js
Cette PR corrige le problème d’erreur 500 pouvant arriver lorsqu’un numéro ne possède pas de type de position.
Elle ajoute également une fonction pour afficher correctement les numéros avec un suffixe numérique.
Pour tester, utiliser [Route d’Amien, Villers-Bretonneux](https://adresse.data.gouv.fr/base-adresse-nationale/80799_0020#15.26/49.87065/2.5081)
=> Corrige erreur 500 & Affichage des suffixes numériques

components/ban-search.js
Un message d’erreur apparaissait lorsqu’on effaçait toutes les lettres dans la barre de recherche ou lorsqu’on écrivait seulement une ou deux lettres.
Cette PR ajoute une condition qui permet de lancer la recherche uniquement si au moins trois caractères ont été entrés.
(Cette limite vient de l’API)
=> Corrige l’erreur lors de la recherche sur la page d’accueil

components/commune/bal-alerts.js, components/commune/bal-quality.js, pages/commune/[codeCommune].js
Lors d'un moissonnage, seules les lignes valides alimentent la BAN. Les lignes en erreur sont filtrées sans que le producteur de la donnée en ait connaissance.
Cette PR permet d'avertir sur la page commune si des erreurs ont été rencontrées et combien de ligne sont n'ont pas pu alimenter la BAN.
------
⚠️ DRAFT : Le `moissonneur-bal` ne renvoi pas encore les informations nécessaires dans `clent.extra` (développement en cours)
=> Gestion des erreurs détectées pendant un moissonnage

components/commune/bal-quality.js
Certaines page communes sont actuellement inaccessible erreur 500 si elle n'ont pas de currentRevision pour leur bal.
exemple https://adresse.data.gouv.fr/commune/22084
=> page commune en erreur pour les bal sans currentRevision

pages/base-adresse-nationale.js
Si l'adresse a plus de 2 positions, l'affichage de la carte provoquait une erreur 500.
exemple 
[261 Rue de la Cascade,Courbouzon - 39169 (4 positions : 1 entrée, 1 batiment,  2 logements )](https://adresse.data.gouv.fr/base-adresse-nationale/39169_0035_00261)
attendu
fix #1341
=> Fix le calcul du bounding box pour les adresses multi-positions

components/commune/bal-state.js
La section statistiques s'affiche même lorsque que la commune ne dispose d'aucun numéro.
Cette PR n'affiche les statistiques que si la commune comporte des numéros.
=> N'affiche les statistiques des communes que lorsqu'elle contiennent des numéros

lib/util/compute.js, lib/util/contours-communes.js, server/deploiement.js
Une erreur s'est glissée dans la mise à jour des données utilisée pour la carte de l'état du déploiement des BAL. 
Le calcul, prévu pour s'effectuer à chaque fois que le temps de cache était terminé, n'était en réalité pas relancé et seul les données générées au lancement du serveur étaient utilisées.
=> Correction de la mise à jour des données de déploiement des BAL

components/maplibre/ban-map/layers.js
l'affichage des multi positions sur la carte ne reprend pas le suffixe de l'adresse.
affichage du numero (dont suffixe) et du type d'entrée
#1353
=> Map :suffixe du numeros manquant pour les multi-positions

components/base-adresse-nationale/numero/coordinates-copy.js, components/base-adresse-nationale/positions-types.js, components/icons/target-lock.js, components/maplibre/ban-map/index.js, components/maplibre/map.js, pages/base-adresse-nationale.js
Le chargement de la page numero affiche une fiche du numéro indiquant sa ou ses positions et une carte.
Si le numero possède plusieurs positions l'utilisateur peut avoir du mal à les distinguer dans la carte ou les "perdre" si il se déplace sur la carte.
Cette pr vise à donner la posibilité  à l'utilisateur de localiser ces positions.
- ajout d'un bouton/lien à chaque position qui recentre la carte sur la position
( avec modification du style du libellé pour ne pas confondre avec un bouton)
*Avant*
*Après*
- modification du comportement du bouton cible dans la carte (recentre sur l'ensemble des positions et pas seulement la position du géocodage)
=> Acces aux positions d'un numéros

pages/base-adresse-nationale.js
L'accés au [numero via une url sans hash](https://adresse.data.gouv.fr/base-adresse-nationale/60667_0280_00033) est cadré sur
- le displayBBox, qui correspond pour le moment à la position "préférée" (remontée par le geocodage ou autre représentation à 1 position)
- ou si il y a plusieurs positions, sur l'étendu de l'ensemble des points
l'accés au [numero via une url avec hash](https://adresse.data.gouv.fr/base-adresse-nationale/60667_0280_00033#18.61/49.31465/2.7411) est cadré suivant les parametres du hash (zoom , centre ...).
ce comportement n'est pas respecté pour un premier chargement : [cadrage hors des positions](https://adresse.data.gouv.fr/base-adresse-nationale/60667_0280_00033#17.76/49.312178/2.739666 "le cimetière au sud des positions")
est redirigé sur l'entrée [la position …
=> fix respect du hash sur chargement de la carte

lib/format-numbers.js
This commit aims to fix the "text content does not match server-rendered HTML" error that appear depending on the running environnement. The error appears when the running context has a locale different from 'fr-FR'. The error appears in a local deployment with docker for example, or in production (do not appear with local 'dev' mode without docker).
=> Fix default num formater locale not to depend on runner context

components/maplibre/ban-map/layers.js
Sur l'explorateur adresse le label des toponymes est trop petit à un au niveau de zoom.  Etant une information que l'on souhaite mettre en valeur, la police doit rester de taille convenable.
=> Garder les labels de toponyme bien visible sur la carte

layouts/base-adresse-nationale.js
Possible coquille sur le calcul rendu de la hauteur de la zone centrale sur "mobile" dans l'explorer.
La zone pourrait etre ramassé ou les boutons (explorer, carte) de sélection en dessous non accessible.
=> rendu mobile : fix la disposition dans l'explorer

components/bases-locales/bal-cover-map.js, components/maplibre/map.js, components/search-input/index.js, components/search-input/search-selected.js, components/search-input/stats-search-item.js, data/geo/departement-center.json, hooks/stats-deploiement.js, lib/api-ban.js, lib/api-geo.js, lib/util/compute.js, pages/deploiement-bal.js, server/deploiement.js
Afin de monitorer leurs actions, les EPCI ont besoin de pouvoir filtrer les données sur la carte du déploiement BAL
- Filtrage par EPCI
- Filtrage par département
- Possibilité de télécharger le CSV des données affichées sur la carte quand un filtre est actif
- Basculer sur la branche ban-plateform : https://github.com/BaseAdresseNationale/ban-plateforme/pull/160
- Lancer le script worker de ban-plateform pour mettre à jour la metric "bal-stats"
=> Filtrer la carte déploiement BAL par EPCI ou département

components/maplibre/styles/vector.json
Dans l'explorer la carte vectorielle affiche des contours administratifs suivant les données de france-vector. 
L'outil mes-adresses utilise découpage-administratif pour les contours , afin d'harmoniser le rendu et les limites cette même source sera utilisée.
[france-vector](https://openmaptiles.geo.data.gouv.fr/data/france-vector/#14/48.85013/2.30810)
[découpage-administratif](https://openmaptiles.geo.data.gouv.fr/data/decoupage-administratif/#12/-21.90227/166.06934)
- Garder un rendu similaire
- Pas de gestion supplémentaire (bouton) pour afficher la couche
- un affichage des communes un peu plus tôt dans les zooms (10 vs 11)
- un léger "dégradé" sur la couleur des lignes régions / départements / communes
#1523
=> Affichage des contours administratifs via decoupage-administratif

lib/util/contours-communes.js
- La commune de Terval est tronquée sur la carte de déploiement BAL. C'est parce que c'est une nouvelle commune créée au 1 janvier 2023 et que l'on utilise le millésime 2022 des contours de communes. 
- En mettant à jour, l'URL ça résout le problème pour Terval mais y'avait-il une raison pour laquelle nous voulions garder les contours communes 2022?
=> Mise à jour de l'URL des contours communes pour 2023

components/maplibre/ban-map/layers.js
Certaines couleurs sembles trop proches ou pas assez contrastées et mènent parfois à confusion.
Palette actuelle
https://davidmathlogic.com/colorblind/#%234dac26-%232c7bb6-%23118571-%23a6611a-%23455d7a-%23fecd51-%23d7191c-%237b3294
Changement de la palette de couleurs des sources d'adresse sur l'explorateur : 
[x] Utilisation de la palette Wong afin d'avoir des couleurs distinctes et plus adaptées aux daltoniens et à nos fonds carto.
https://davidmathlogic.com/colorblind/#%23000000-%23E69F00-%2356B4E9-%23009E73-%23F0E442-%230072B2-%23D55E00-%23CC79A7
[x] suppression de l'insee de la légende, cette donnée n'est plus remonté.
#1415
=> Améliorer la distinction entre les sources (couleurs) d'adresse sur l'explorateur

pages/contribuer.js
#1342
Besoin : mettre sur le site adresse l'accès à la plateforme osmose d'animation du collectif des usagers de la BAN.
Solution : ajout d'un bouton permettant d'y accéder sur la page contribuer.
Ajout sur la page contribuer :
=> Add new Button to contribute page

events.json
Ajout de l'adresse lab du 26 Septembre 2023, il n'est pas prévu de mettre un bouton "rejoindre" dans lévènement"
=> Ajout adresse lab

components/fantoir/voie-information.js
Avec le changement de format du fichier fantoir -> Topo l'information clef rivoli disparait.
On ne doit plus l'afficher dans l'explorateur.
Voici le résultat : 
fix #1569
=> plus de clef rivoli dans topo

pages/donnees-nationales/index.js
Suppression du téléchargement des anciennes bases de données IGN sur la page d'accès aux données (https://adresse.data.gouv.fr/donnees-nationales) 
Résultat de la modification
Fix #1546
=> suppression telechargement données ign

components/header.js, pages/contribuer.js
Ajout du lien "Rejoignez le collectif des usagers" dans l'onglet utilisateurs
Le lien pointe vers /contribuer#osmose qui renvoie directement sur la bonne rubrique de la page contribuer
Fix #1561
=>  ajout lien onglet utilisateurs

.env.sample, components/bases-locales/deploiement-bal/bal-card.js, components/bases-locales/deploiement-bal/bal-cover-map.js, components/bases-locales/deploiement-bal/commune-bal-list.js, components/bases-locales/deploiement-bal/panel-bal.js, components/bases-locales/deploiement-bal/panel-source.js, components/bases-locales/deploiement-bal/status-badge.js, components/doughnut-counter.js, components/maplibre/map-legends.js, lib/mes-adresse-api.js, lib/util/compute.js, package.json, pages/deploiement-bal.js, styles/colors.js, yarn.lock
Le `/dashboard` sur mes-adresses a été fermé
Il faut migrer la partie déploiement des BAL sur la page `deploiement-bal`
- Ajout d'un select dans la légende pour rajouter l'onglet `Suivis du statut des BALs` avec une nouvelle colorimétrie pour les états des BALs
- Ajout des BALs par commune dans le panel de gauche lorsque l'onglet `Suivis du statut des BALs` est sélectionné
https://github.com/BaseAdresseNationale/mes-adresses-api/pull/410
Utiliser la branch `fufeck_refacto-deploiement-bal` de `mes-adresses-api` pour tester
Ne pas oublier les 2 variables environnemental pour le deploy
NEXT_PUBLIC_BAL_API_URL=https://api-bal.adresse.data.gouv.fr/v1
NEXT_PUBLIC_MES_ADRESSES=https://mes-adresses.data.gouv.fr
=> Refacto deployement bal

components/bases-locales/charte/candidacy-form.js
Sur Adresse (https://adresse.data.gouv.fr/bases-locales/charte/organismes) certain liens de partenaire redirige vers une 404 de adresse
C'est parce qu'il manque le https:// au url que c'est redirigé en local
Ajout du `type='url'` au champs url du formulaire de candidature des partenaire de la charte
=> Add type url in partnaire form

components/bases-locales/deploiement-bal/bal-cover-map.js, components/bases-locales/deploiement-bal/panel-bal.js, components/maplibre/map-legends.js, components/maplibre/select-paint-layer.js, lib/mes-adresse-api.js, pages/deploiement-bal.js, styles/colors.js
Après la migration de la page /dashboard de mes adresses vers /deploiement-bal de adresse, il manque quelque fonctionnalité pour que la page soit optimal
PR Mes-adresses-api : https://github.com/BaseAdresseNationale/mes-adresses-api/pull/411
Avec le graphique de publication Bal par defaut:
Avec seulement les communes qui ont des BALs
=> deploiement-bal v2

components/blog-card.js, lib/blog.js, pages/bases-locales/temoignages/[slug].js, pages/bases-locales/temoignages/index.js, pages/blog/[slug].js, pages/blog/index.js, pages/index.js
Fixed nextJS “Large Page Data” warning log on production server. The warning is due to too much data loaded for the Blog block.
This fix configures the Ghost API call with limited named fields.
=> Fix: NextJS Warning log "Large page data"

pages/api-doc/adresse.js
#1529 
L'objectif de cette PR est d'ajouter un texte de présentation de l'API Adresse ainsi que des informations sur que faire si l'on atteint les limites d'appel de l'API.
=> Add presentation text for API Adresse

events.json
Ajout du message : « Il n’est pas nécessaire de « s’inscrire à l’événement ». Le lien d’inscription correspond au lien qu’il faudra utiliser le 12 décembre pour se connecter au webinaire. »
Fix #1661
=> Ajout message pour evenement 12 decembre

components/maplibre/ban-map/index.js, components/maplibre/index.js, components/maplibre/map-legacy.js, components/maplibre/map.js, layouts/base-adresse-nationale.js, package.json, pages/deploiement-bal.js, yarn.lock
Afin d'éviter les mélanges affichage et bouton via react et des fonctions impératives sur la carte (dom et event) qui compliquent la compréhension et sont source de bug, l'utilisation de la lib react-map-gl est proposée.
Cette mise en place permet également de résoudre le bug https://github.com/BaseAdresseNationale/adresse.data.gouv.fr/issues/1552 de désynchronisation carte/ état des outils
fix #1672
Le composant d'initialisation d'une carte change de signature. L'ancien comportement est dans map-legacy.js.
=> Passage de la carte explorateur en React-map-gl

lib/util/analytics-tracker.js, pages/data/[[...path]].js
Actuellement, les téléchargement qui on lieu sur l'URL `/data` ne sont pas comptabilisé parmi les évènements de Matomo. Cette PR a pour but de corriger cette erreur.
- S'assurer d'avoir : 
- Un fichier `.env` à jour 
- Une valeur définit pour la variable `PATH_STATIC_FILE` de ce fichier `.env`, qui pointe sur un dossier de votre disque dur (qui, idéalement, possède quelques fichiers CSV, PDF ou autre - ⚠ Les noms de ces fichiers seront remontés dans Matomo ⚠). Ex : PATH_STATIC_FILE=/User/user_name/repertoire_de_test_possedant_quelques_fichiers/ 
- Des valeurs valide pour les variable `NEXT_PUBLIC_MATOMO_URL` et `NEXT_PUBLIC_MATOMO_SITE_ID` du fichier `.env`
- Un token valide pour la variable `MATOMO_TOKEN_AUTH` du fichier `.env`
- Démarrer le projet en mode DEV : `yarn dev`
- Se rendre …
=> Fix: Analytics do not receive data from backend download

.dockerignore, Dockerfile.dev, components/bases-locales/index.js, components/maplibre/ban-map/index.js, docker-compose.yml, lib/api-ban.js, pages/index.js, pages/programme-bal.js
Currently on adresse.data.gouv, if there is an issue with ban-plateforme API, some pages, the home page included, will display an error message (error 404 or error 500)
This PR aims to withdraw the stats dependencies on : 
- the "Home" page
- the "Programme Bal" page
Before : 
Home page & Programme Bal page  : 
After : 
Home Page : 
--------------------------------------------------------
Programme Bal : 
--------------------------------------------------------
=> Fix home page stats dependencies

components/commune/download-adresses.js
When reaching adresse.data.gouv directly on the 'commune' page URL, an error 500 appears
This PR aims to fix the issue on the 'commune' page by 
- adding a useCallback hook on the download BAL functions
=> Fixed commune page adding react useCallback

components/commune/historique.js
Dans l'application mes-adresses, nous avons besoin de visualiser directement l'historique des publication de BAL.
Ajout d'un id ancre `historical-bal` sur la page commune pour que l'historique soit directement accessible via l'url `/commune/codeCommune#historical-bal`
=> Add anchor historical bal

components/maplibre/map-legacy.js, components/maplibre/map.js, server/index.js
Suite à la migration des flux Géoportail vers la geoplateforme, changement de l'appel à l'image satellite sur le site.
Fix #1708
=> Modification Url appel pour carte Ortho IGN

components/bases-locales/validator/index.js, components/bases-locales/validator/validateur-documentation/index.js, package.json, yarn.lock
- Mise a jour du package validateur-bal v2.18.2 qui prends en compte le format BAL 1.4 et les erreurs relatif a id_ban_commune, id_ban_toponyme et id_ban_adresses
- Un seul nouveau profile mis en ligne pour le moment, pour ne pas trop embrouillé les utilisateur avec les différents profiles du format 1.4
- Mise a jour de la documentation du validateur
=> update: version validateur 2.18.2

package.json, yarn.lock
- Lorsque l'on passait un fichier BAL 1.3 avec le profile 1.3 (default), la page nous disait qu'il manquait les ids ban. Alors que normalement les alertes pour dire que c'est champ ids ban manque ne devrait être que sur le profile 1.4
- Jusqu'a maintenant comme les champs du format BAL ne changeait pas d'une version a une autre, il n'y a pas de systeme pour détecter les champs manquant en fonction de la version du format
Mise a jour de la version validateur-bal v2.18.2 -> v2.18.3, avec un systeme qui detecte les champs manquant en fonction de la version du format du profile utilisé
https://github.com/BaseAdresseNationale/validateur-bal/releases/tag/v2.18.3
=> validateur: v2.18.3

.env.default, components/bases-locales/charte/partner.js, components/search-commune-contact/index.js, lib/api-etablissements-public.js, pages/commune/[codeCommune].js
The api used to get "mairie"  information (name, email, telephone and opening hours) is now deprecated : https://api.gouv.fr/les-api/api_etablissements_publics (deprecated)
The new API to use is the one from the DILA : https://api.gouv.fr/les-api/api-annuaire-administration-services-publics
This PR : 
- Replace the deprecated api by the DILA api
- Format the result to get same format used in our code to display "mairie" information.
1- Clone this branch and start the app
2- Scroll down the main page in the section "Obtenez des informations sur les adresses d’une commune" and search for any "commune". Select a "commune" : it will open the "commune" page with all the related info. (exemple for "Bordeaux" : `localhost:5000/commune/33063` <= adapt the port if you are running the app on …
=> Added new DILA api route to get mairie info

events.json
Ajout événement rencontre utilisateurs le 04 Juin
Fix #1736
=> Ajout events 04 Juin Rencontre utilisateurs

lib/ban.js
Issue #1738 
Dans le panneau latéral, les suffixes sont collés.
Exemple :
avant : 
Après :
=> Add space between number and suffix

events.json
Ajout adresse Lab T3 2024 du mardi 25 Juin 
Fix: #1754
=> Ajout adresse Lab T3 2024

lib/api-etablissements-public.js
Sur adresse.data.gouv.fr (par exemple sur la page commune https://adresse.data.gouv.fr/commune/48009) n'avaient pas le bon mail pour les contacter.
Pour la commune 48009,ça affiche [mairie.stecolombepeyre@orange.fr](mailto:mairie.stecolombepeyre@orange.fr) alors que cela devrait être [peyreenaubrac@orange.fr](mailto:peyreenaubrac@orange.fr).
fix: #1514
=> Probleme mail commune

views/data/data-entry.js, views/data/data.js
Sur la page : https://adresse.data.gouv.fr/data/ban/adresses, il y a un décalage d'1 mois sur l'affichage des dates pour les données disponibles.
apres
fix #1753
=> Probleme date sur page telechargement des donnees 

Dockerfile, components/bases-locales/deploiement-bal/panel-bal.js, components/maplibre/ban-map/index.js
Erreur constatée lors du déploiement sur la nouvelle infrastructure
Dans les fichiers :
- components/bases-locales/deploiement-bal/panel-bal.js : la fonction setDataStatsWithBal est déclarée après
- components/maplibre/ban-map/index.js : la fonction highLightAdressesByProperties est déclarée après initialisation
Ajout d'un USER node avant démarrage pour basculer sur exécution non root dans le container docker 
fix:#1757
=> move function to avoid declare after use error

components/api-doc/api-adresse/curl-doc.js
Dans la documentation de l'API de dépot
Le paramètre attendu est result_score et non score
=> typo curl-doc.js

components/bases-locales/charte/partenaires/moissonneur-bal/index.js, components/bases-locales/charte/partenaires/moissonneur-bal/revisions/revision-item.js, components/bases-locales/charte/partenaires/moissonneur-bal/revisions/revisions-list.js
Le button de l'accordion est maintenant entièrement cliquable 
Le nom de la commune est affichée en plus du code
=> fix: correct page partenaire

components/bases-locales/deploiement-bal/panel-source.js, hooks/stats-deploiement.js
This PR adds on the page `/deploiement-bal` the stats about ban-id : 
- number of commune that have ban ids (and its percentage)
- number of addresses that have the ban ids (and its percentage)
=> Added ban-id stat doughnuts on deploiement-bal page

components/bases-locales/deploiement-bal/bal-card.js, components/bases-locales/deploiement-bal/commune-bal-list.js, components/bases-locales/deploiement-bal/panel-bal.js
Depuis la migration postgres de mes-adresses la page /deploiement-bal est cassé.
On ne voit pas le graph et les bal, si on selectionne un departement et qu'on est sur l'onglet `suivi mes-adresses`
Remplacer les champs `_id` et `'_updated` par `ìd` et `updatedAt` dans les pages de  /deploiement-bal
=> fix: /deploiement-bal suivi mes adresses

server/proxy-api-depot.js
Les bals de plus de 10mo sont rejeter dans le formulaire de publication par la route `/proxy-api-depot/revisions/:revisionId/files/bal` alors que la limit a été passé a 50mo
=> fix: formulaire upload file bal 50m

components/bases-locales/deploiement-bal/bal-cover-map.js
- Dans l'onglet `suivi de mes adresses` les BAL en conflit étaient affiché `Autre source` (exemple Gonneville le-theil)
- Dans l'onglet `suivi de mes adresses` si une bal avait une ancienne bal, c'est cette derniere qui était affiché (exemple Nouainville, qui est actuellement publié avec le formulaire mais on affichait la bal en brouillon)
Ajouter des filtre sur les couleurs des features
=> fix: /deploiement-bal color features

components/base-adresse-nationale/numero/download-certificate.js, components/base-adresse-nationale/numero/index.js, pages/base-adresse-nationale.js
When a district has its `certificate` feature activated, a link is available on its addresses (that are certified and have an ban id and at least one parcel). 
This PR improve the user experience
- The is no more loading on client side (the district config is fetched from server side)
=> Improved certificate experience

src/app/blog/[slug]/components/AsideContent.tsx, src/app/blog/[slug]/page.tsx, src/layouts/Footer.tsx
Close #1944
Modifications à faire suite discussion sur mattermost
Ne pas afficher le chapeau sur l'article du blog
Supprimer le bloc "partager la page"
Newsletter : problème de lien
Remonter facebook dans "Nous suivre"
Supprimer la partie " A voir également"
=> Modif diverses blog

src/components/SectionSearchBAN/SectionSearchBAN.tsx
Retour en arrière sur les boutons sur la home page en dessous de la barre de recherche.
Mise en place de lien simple comme avant
Fix : #1928
=> Rollback sur les boutons recherche home

src/app/api/certificat/[idAdresse]/route.tsx, src/app/carte-base-adresse-nationale/components/PanelAddress/PanelAddressFooter.tsx, src/app/carte-base-adresse-nationale/page.tsx, src/app/carte-base-adresse-nationale/types/LegacyBan.types.ts, src/app/commune/[codeCommune]/ResumeDistrict.tsx, src/app/commune/[codeCommune]/page.tsx, src/lib/api-ban.ts, src/lib/ban.ts, src/types/api-ban.types.ts
The BAN lookup api now retrieve the `config` (config of the district) and the `withBanId` (boolean that says if the address is from our new technical architecture) fields from the address.
This PR aims to : 
- reduce the number of calls to the ban-plateforme API to create a certificate by retrieving the district `config` directly from the address (and not from the district that was requiring a call to our main database).
- add the condition `withBanId` to the certificate as the certificate can only be activated on data that is part of our new system.
=> [New App] - Migrated get config from district to address

components/base-adresse-nationale/numero/index.js, lib/api-ban.js, lib/ban.js, pages/api/certificat/pdf/[id-adresse].js, pages/base-adresse-nationale.js
The BAN lookup api now retrieve the `config` (config of the district) and the `withBanId` (boolean that says if the address is from our new technical architecture) fields from the address.
This PR aims to : 
- reduce the number of calls to the ban-plateforme API to create a certificate by retrieving the district `config` directly from the address (and not from the district that was requiring a call to our main database).
- add the condition `withBanId` to the certificate as the certificate can only be activated on data that is part of our new system.
=> [Current App] - Migrated get config from district to address

src/app/carte-base-adresse-nationale/components/PanelDistrict/PanelDistrict.tsx
Fixing interface issue displaying a '0' :
=> Fixed district detail on certified addresses

next.config.mjs
Fix redirection for [adresse.data.gouv.fr/api-doc/adresse](https://adresse.data.gouv.fr/api-doc/adresse)  ==> [https://adresse.data.gouv.fr/outils/api-doc/adress](https://adresse.data.gouv.fr/outils/api-doc/adresse)
=> Fix bug redirection route

src/app/carte-base-adresse-nationale/components/PanelAddress/PanelAddressHeader.tsx, src/app/carte-base-adresse-nationale/components/PanelMicroToponym/PanelMicroToponymHeader.tsx, src/app/contenu-de-la-ban/page.tsx, src/app/decouvrir-la-BAN/page.tsx, src/app/outils/page.tsx, src/app/page.tsx, src/app/ressources-et-documentations/page.tsx, src/components/SectionHero/SectionHero.stories.tsx, src/components/SectionSearchBAN/SectionSearchBAN.tsx, src/data/sample-actions.json, src/data/sample-bal-info.json, src/data/sample-ban-info.json
Sur firefox les images pouvaient ne pas s'afficher si on commence la navigation pas une url profonde http://adresse.data.gouv.fr//outils/telechargements et revenir sur l'accueil par exemple
fix #1993
=> fix url image pour firefox

src/views/data/utils/helper.ts
Prise en compte des requêtes Head sur les fichiers : évite le téléchargement.
Ajout de last-Modified sur les fichiers fournis sur adresse.data.gouv.fr/data pour réduire les demandes de téléchargements et les clients de vérifier la fraicheur et gérer leur cache.
vérifiable par exemple dans un navigateur
(outil developpeur)
ou en commande
(HTTP get affiche l'entete)
curl -i https://adresse.data.gouv.fr/data/ban/adresses/latest/csv/lieux-dits-974-beta.csv.gz
HTTP HEAD
curl -I https://adresse.data.gouv.fr/data/ban/adresses/latest/csv/lieux-dits-974-beta.csv.gz
=> Ajout de  last-Modified entete http sur les fichiers à télécharger

src/views/data/utils/helper.ts
une HEAD HTTP Request sur les fichiers en téléchargement ne renvoie pas les les bonnes informations (mixed), la requete continuai et gênerai un html
BUG 
Content-Type , la taille, sont aberrants pour la ressource demandée
```console
curl -I https://adresse.data.gouv.fr/data/ban/adresses/2025-01-29/addok/addok-france-bundle.zip 
HTTP/1.1 200 Connection established
HTTP/1.1 200 OK
Date: Thu, 30 Jan 2025 16:19:05 GMT
Content-Type: text/html; charset=utf-8 
Content-Length: 29040
Connection: keep-alive
Content-Disposition: attachment; filename="addok-france-bundle.zip"
Last-Modified: Thu, 30 Jan 2025 04:01:51 GMT
ETag: "cpx33ug08gmcd"
X-Powered-By: Next.js
Cache-Control: private, no-cache, no-store, max-age=0, must-revalidate
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000; …
```
=> hotfix HEAD request

dockerfile
As the nextjs app is using the 'standalone' mode, there are useless folders that are copied into the image (such as node_modules) that are already copied in the standalone folder
- Removing those useless folder reduces the docker image size by more than **1Go**
- Using alpine image version also reduces the docker image size by more than **1Go**
Result : image size reduced from **3.15Go** to **1.19Go**
=> Reduced docker image size from 3.15Go to 1.19Go

src/app/carte-base-adresse-nationale/components/LoadingBar/LoadingBar.styles.tsx, src/app/carte-base-adresse-nationale/layout.styles.tsx, src/app/carte-base-adresse-nationale/layout.tsx, src/app/carte-base-adresse-nationale/page.styles.tsx, src/app/carte-base-adresse-nationale/page.tsx, src/components/SearchBAN/search-input/SearchInput.styles.tsx, src/components/SearchBAN/search-input/SearchInput.tsx
Some components are triggering constant style calculation that are caused by animation running, even if display is turned off (display : 0)
=> Paused animations when not displayed to stop re-rendering 

src/components/FormulaireDePublication/index.tsx, src/components/FormulaireDePublication/steps/HablitationMethod.tsx, src/lib/api-depot.tsx, src/types/api-depot.types.ts
Depuis la migration de l'api-depot les type `revision` et `habilitation` ont le `_id` remplacer par `id` ce qui créer de nombreux petit bug
=> hotfix: change type revision and habilitation

package-lock.json, package.json
- Le validateur en ligne ne marche plus a cause d'une redirection casser dans la package
- Mise a jour du package corrigé 2.22.1
=> hotfix: update package validateur to 2.22.1

src/app/blog/[slug]/page.tsx
**Contenu**
Force le rendu dynamique de la page blog. 
**Contexte**
Les pages blog sont peu visité, et  sont en cache par défaut.
Si l'article est mis à jour, la page du site n'est pas recalculer : Nous n'avons pas de back office pour relancer les regénérations des pages en cache ou static (de plus dans un environnement multi node).
Avec ces constats, le rendu dynamique semble une solution adapté pour que les modifications sur les articles soient accessibles.
=> Force la page blog à un rendu dynamique

src/layouts/Header.tsx
Changement : Le bouton "La documentation" dans le bandeau du haut redirige vers la page "Documentation adressage" (https://adresse.data.gouv.fr/documentation-bal)
=> fix: update doc link

src/components/Commune/CommuneActions/index.tsx
Temporairement il faut désactiver l'activation du certificat d'adressage pour traiter les demandes en cours et améliorer le système.
=> Desactivation demande activation certificat adressage

src/components/Partenaires/APIDepot/api-depot-revision/APIDepotRevisionItem.tsx
Fix: Répare la page partenaire du pays basque : [https://adresse.data.gouv.fr/partenaires/64ecadcef5e9efbd57bdd006](https://adresse.data.gouv.fr/partenaires/64ecadcef5e9efbd57bdd006)
=> fix: page partenaire pays basque

src/components/Commune/CommuneCertificationBar/index.tsx, src/components/Commune/CommuneUpdatesSection.tsx, src/lib/api-depot.tsx
Les horaires de a liste des révision n'est pas bien converti en prod et avance de 2h
-> Petit fix pour avoir la bonne horaire
=> fix: horaires list past revisions

src/app/carte-base-adresse-nationale/components/PanelAddress/PanelAddressFooter.tsx
Modification du wording pour le certificat d'adressage sur la carte s'il est indisponible pour la commune
Fix : #2162 
Après modification voici le résultat :
=> issue2162: Modification wording certificat

src/app/layout.tsx
Comme le cog est fini maintenant, il faut supprimer le bandeau d'alertes sur le site.
Fix: #2167
=> Suppression bandeau alerte Cog 2025

src/app/outils/telechargements/page.tsx
Sur la page téléchargement, suppression du bloc alerte passage cu cog 2025
Fix : #2173
=> Suppresion du bloc alerte page telechargement

src/app/layout.tsx
Suppression du bandeau actualité mis en place le 24 Juin pour la maintenance.
Fix: #2177
=> Suppression du bandeau de maintenance 24 Juin

src/components/Partenaires/Moissonnage/MoissonneurBAL.tsx, src/components/Partenaires/Moissonnage/moissonneur-revision/MoissonneurRevisionItem.tsx
Sur les consoles de visualisations des partenaires qui moissonnent, il manque l'indication lorsque la BAL est publiée via un autre client (Mes Adresses). Exemple avec Mayran, sur la page du SMICA on a l'impression que tout est ok sur cette commune, le moissonnage n'a aucune erreur, les mises à jour bien récupérées... saufc que Mayran est publié via Mes Adresses https://adresse.data.gouv.fr/commune/12142
- Optimisation: lancement des requêtes pour récupérer les harvests et révisions du moissonneur lorsque l'on ouvre l'Accordion de la source, pour éviter de lancer des 100ain requêtes au chargement de la page comme pour https://adresse.data.gouv.fr/partenaires/64ecadcef5e9efbd57bdcfe7
- Ajout de la comparaison avec la revision courante pour savoir si la révision du moissonneur a été …
=> fix: console moissonneur when other source published

src/data/ban-events.json
Sur les 2 événements de Septembre BAN, faire les modifications ci-dessous:
- sur l'adresse lab, rajouter au titre Adresse-Lab T3 2025
- sur la rencontre des utilisateurs nationaux, enlever le #9
- Mettre un tag Base Adresse Nationale pour les 2 événements au lieu de BAN
-  Harmoniser les tags en mettant TECHNIQUE UTILISATEURS BASE ADRESSE NATIONALE
Rendu des 2 événements:
=> Modif evenements BAN septembre

.env.default
Modification lien flux rss sur la page blog et le footer qui renvoie actuellement une erreur 404
Il faut changer  dans le .env la valeur de la variable : NEXT_PUBLIC_SOCIAL_NETWORKS_URL_RSS par : https://ghost.adresse.data.gouv.fr/rss/
Fix: #2245
=> Modification lien flux rss

src/components/SearchBAN/SearchBAN.tsx
Ajout de l'information arrondissement pour la recherche sur les villes de paris, Lyon, Marseille
Si nous sommes dans le cas de ces villes, nous affichons l'arrondissement pour toutes les rues de la recherche, ce qui permet de distinguer les rues identiques qui sont sur plusieurs arrondissements.
Fix : #2170
=> Ajout info arrondissement pour PML

.env.default, src/app/stats/[slug]/route.tsx
Cette PR fixe le problème de connexion du site vers les API Matomo.
Pour son bon fonctionnement, il est nécessaire de configurer la variable d'environnement `MATOMO_TOKEN_AUTH` avec un token généré depuis l'interface d'administration de Matomo.
=> Use Matomo token Auth for Stats API

public/markdown/apis/service-geocodage--intro.md, public/markdown/apis/service-geocodage.md
Sur la page "Service de gécodage de la géoplateforme", ajout du texte sur l'actualisation du geocodeur.
Modification du texte sur les limites d'usage
Fix: #2276
=> Ajout texte publication des données geocodeur
